### ISSUE TITLE
IME Error when entering text in a new paragraph (Android)

### ISSUE THREAD

**Issue by transcendr** [superlistapp/super_editor#1006]
Repro: Run the example app. Place the caret at the end of the document and type a single character.  The character is inserted as expected, however the exception is triggered.

Exception:
```
════════ Exception caught by services library ══════════════════════════════════
The following StateError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Bad state: No element

When the exception was thrown, this was the stack
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      _DocumentImeInteractorState.updateEditingValueWithDeltas
#2      TextInput._handleTextInputInvocation
#3      TextInput._loudlyHandleTextInputInvocation
#4      MethodChannel._handleAsMethodCall
#5      MethodChannel.setMethodCallHandler.<anonymous closure>
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#7      _invoke2 (dart:ui/hooks.dart:186:13)
#8      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#9      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#10     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: []}])
════════════════════════════════════════════════════════════════════════════════
```

Associated event logs:

```
Fatal Exception:  Bad state: No element. Error thrown Instance of 'ErrorDescription'.
       at _GrowableList.last(_GrowableList.java)
       at _DocumentImeInteractorState.updateEditingValueWithDeltas(document_input_ime.dart:298)
       at TextInput._handleTextInputInvocation(text_input.dart:1814)
       at TextInput._loudlyHandleTextInputInvocation(text_input.dart:1701)
       at MethodChannel._handleAsMethodCall(platform_channel.dart:536)
       at MethodChannel.setMethodCallHandler.<fn>(platform_channel.dart:529)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:387)
```

IME Logs:
```
I/flutter (13450): (16.195) editor.ime > FINE: Text:
I/flutter (13450): '. '
I/flutter (13450): (16.195) editor.ime > FINE: Converting doc selection to ime selection: [DocumentSelection] -
I/flutter (13450):   base: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
I/flutter (13450):   extent: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream)))
2
I/flutter (13450): (16.195) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
I/flutter (13450): (16.196) editor.ime > FINE: Start IME position: TextPosition(offset: 2, affinity: TextAffinity.downstream)
I/flutter (13450): (16.196) editor.ime > FINE: End IME position: TextPosition(offset: 2, affinity: TextAffinity.downstream)
I/flutter (13450): (16.196) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (16.196) editor.ime > INFO: Sending new text editing value to OS: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter (13450): (16.196) editor.ime > FINE: IME value after applying deltas: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter (13450): (18.694) editor.ime > INFO: Received edit deltas from platform: 1 deltas
I/flutter (13450): (18.695) editor.ime > INFO: Instance of 'TextEditingDeltaInsertion'
I/flutter (13450): (18.695) editor.ime > FINE: IME value before applying deltas: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter (13450): (18.696) editor.ime > INFO: Applying 1 IME deltas to document
I/flutter (13450): (18.696) editor.ime > INFO: Applying delta: Instance of 'TextEditingDeltaInsertion'
I/flutter (13450): (18.696) editor.ime > FINE: Inserted text: "."
I/flutter (13450): (18.696) editor.ime > FINE: Insertion offset: 2
I/flutter (13450): (18.696) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (18.696) editor.ime > FINE: Composing: TextRange(start: 2, end: 3)
I/flutter (13450): (18.697) editor.ime > FINE: Old text: ". "
I/flutter (13450): (18.697) editor.ime > FINE: Inserting text: ., insertion offset: 2, ime selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (18.698) editor.ime > FINE: Inserting "." at position "TextPosition(offset: 2, affinity: TextAffinity.downstream)"
I/flutter (13450): (18.698) editor.ime > FINE: Serializing document to perform IME operation
I/flutter (13450): (18.698) editor.ime > FINE: Creating an IME model from document and selection
I/flutter (13450): (18.699) editor.ime > FINE: IME serialization:
I/flutter (13450): '. '
I/flutter (13450): (18.699) editor.ime > FINE: Converting IME insertion offset into a DocumentSelection
I/flutter (13450): (18.701) editor.ime > FINE: Creating doc selection from IME selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (18.701) editor.ime > FINE: Removing arbitrary character from IME selection
I/flutter (13450): (18.701) editor.ime > FINE: Adjusted IME selection is: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (18.703) editor.ime > FINE: Updating the Document Composer's selection to place caret at insertion offset:
I/flutter (13450): [DocumentSelection] -
I/flutter (13450):   base: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
I/flutter (13450):   extent: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream)))
I/flutter (13450): (18.704) editor.ime > FINE: Inserting the text at the Document Composer's selection
I/flutter (13450): (18.722) editor.ime > INFO: Document composer (481828253) changed. New selection: [DocumentSelection] -
I/flutter (13450):   base: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
I/flutter (13450):   extent: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
I/flutter (13450): (18.722) editor.ime > FINE: Insertion successful? true
I/flutter (13450): (18.761) editor.ime > FINE: Done applying deltas. Serializing the document and sending to IME.
I/flutter (13450): (18.761) editor.ime > FINE: Syncing IME with Doc and Composer, given composing region: TextRange(start: 2, end: 3)
I/flutter (13450): (18.761) editor.ime > FINE: Creating an IME model from document and selection
I/flutter (13450): (18.762) editor.ime > FINE: IME serialization:
I/flutter (13450): '.'
I/flutter (13450): (18.762) editor.ime > FINE: Previous doc serialization did prepend? true
I/flutter (13450): (18.762) editor.ime > FINE: Desired composing region: TextRange(start: 2, end: 3)
I/flutter (13450): (18.762) editor.ime > FINE: Did new doc prepend placeholder? false
I/flutter (13450): (18.762) editor.ime > FINE: Creating TextEditingValue from document. Selection: [DocumentSelection] -
I/flutter (13450):   base: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
I/flutter (13450):   extent: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
I/flutter (13450): (18.763) editor.ime > FINE: Text:
I/flutter (13450): '.'
I/flutter (13450): (18.763) editor.ime > FINE: Converting doc selection to ime selection: [DocumentSelection] -
I/flutter (13450):   base: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
I/flutter (13450):   extent: ([DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
2
I/flutter (13450): (18.763) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "748c9c21-578e-4a2f-99d5-ddaba056082c", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
I/flutter (13450): (18.764) editor.ime > FINE: Start IME position: TextPosition(offset: 1, affinity: TextAffinity.downstream)
I/flutter (13450): (18.764) editor.ime > FINE: End IME position: TextPosition(offset: 1, affinity: TextAffinity.downstream)
I/flutter (13450): (18.764) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false)
I/flutter (13450): (18.764) editor.ime > INFO: Sending new text editing value to OS: TextEditingValue(text: ┤.├, selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 1))
I/flutter (13450): (18.765) editor.ime > FINE: IME value after applying deltas: TextEditingValue(text: ┤.├, selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 1))
I/flutter (13450): (18.851) editor.ime > INFO: Received edit deltas from platform: 0 deltas
I/flutter (13450): (18.852) editor.ime > FINE: IME value before applying deltas: TextEditingValue(text: ┤.├, selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 1))
I/flutter (13450): (18.852) editor.ime > INFO: Applying 0 IME deltas to document
I/flutter (13450): (18.852) editor.ime > FINE: Done applying deltas. Serializing the document and sending to IME.
```

**Comment by angelosilvestre** [comment]
@transcendr This seems to be already fixed in the `stable` branch.

**Comment by matthew-carroll** [comment]
@transcendr can you please confirm whether this issue is fixed with the latest Super Editor and Flutter stable release?

**Comment by transcendr** [comment]
@matthew-carroll @angelosilvestre apologies for having missed this. Our team has confirmed that is resolved now.  Thanks!
