### ISSUE TITLE
[SuperEditor] Cannot add an ImageNode to the middle of a ParagraphNode

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1018]
If a `ParagraphNode` is empty, I can add an `ImageNode` without a problem.

If a `ParagraphNode` contains text (and the selection is anywhere within the node) and an `ImageNode` is added, the following error occurs:

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following _Exception was thrown during a scheduler callback:
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received: TextPosition(offset: 0, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack
#0      _BoxComponentState.getRectForPosition
box_component.dart:187
#1      _SingleColumnDocumentLayoutState.getRectForPosition
_layout.dart:220
#2      _IOSDocumentTouchInteractorState._positionCaret
document_gestures_touch_ios.dart:879
#3      _IOSDocumentTouchInteractorState._updateHandlesAfterSelectionOrLayoutChange
document_gestures_touch_ios.dart:373
#4      _IOSDocumentTouchInteractorState._onDocumentChange.<anonymous closure>
document_gestures_touch_ios.dart:343
#5      SchedulerBinding._invokeFrameCallback
binding.dart:1289
#6      SchedulerBinding.handleDrawFrame
binding.dart:1227
#7      SchedulerBinding._handleDrawFrame
binding.dart:1076
#8      _invoke (dart:ui/hooks.dart:145:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#10     _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received: TextPosition(offset: 0, affinity: TextAffinity.downstream)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════
```

I've modified the [example editor](https://github.com/superlistapp/super_editor/blob/main/super_editor/example/lib/demos/example_editor/example_editor.dart) to add an "add image" button to the standard `KeyboardEditingToolbar` which calls the following method:

```
  void _addImage() {
    commonOps.insertImage('https://storage.googleapis.com/cms-storage-bucket/d406c736e7c4c57f5f61.png');
  }
```

**Comment by Jethro87** [comment]
cc @matthew-carroll
