### ISSUE TITLE
[SuperEditor] 0.2.6 pub mobile list item regression

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1220]
I'm waiting for #1209 to be solved before updating to stable/atomic commands, so I tried the latest pub version 0.2.6. However, I noticed a regression with regard to list items. This has been tested on iOS.

Previously, entering "- " automatically converted to a bullet after the space. Now, this conversion doesn't happen until an additional character is hit (e.g., "- H"), and when it is converted, the carat is in the wrong position and an error is thrown.

This also happens for ordered lists (e.g., "1. H").

https://github.com/superlistapp/super_editor/assets/6467808/0ee8dec5-fcee-487b-bcf9-5759f798c56c

```
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '1. N'
IME position: TextPosition(offset: 4, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack
#0      DocumentImeSerializer._imeToDocumentPosition
document_serialization.dart:271
#1      DocumentImeSerializer.imeToDocumentSelection
document_serialization.dart:164
#2      TextDeltasDocumentEditor._applyInsertion
document_delta_editing.dart:153
#3      TextDeltasDocumentEditor.applyDeltas
document_delta_editing.dart:69
#4      DocumentImeInputClient.updateEditingValueWithDeltas
document_ime_communication.dart:215
#5      TextInput._handleTextInputInvocation
text_input.dart:1857
#6      TextInput._loudlyHandleTextInputInvocation
text_input.dart:1746
#7      MethodChannel._handleAsMethodCall
platform_channel.dart:547
#8      MethodChannel.setMethodCallHandler.<anonymous closure>
platform_channel.dart:540
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
binding.dart:479
#10     _invoke2 (dart:ui/hooks.dart:174:13)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 4, oldText: 1. , selectionAffinity: TextAffinity.downstream, deltaEnd: 3, deltaText: N, deltaStart: 3, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 4, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════
```

cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@Jethro87 if this is a bug against the released version, we'll need to create a hotfix and do another release from a new hot fix branch. Do you feel that you need that, or is it better for us to focus on getting atomic commands to work for you, where I assume this problem doesn't exist?

**Comment by Jethro87** [comment]
@matthew-carroll I tested this with atomic commands and it doesn't appear to be an issue. I'm ok waiting for the other atomic commands issues to be solved, so I don't need a hotfix.

One reason you *may* want to do a hotfix, in my opinion, is public perception of the package, as this isn't a great experience for new super editor users. On the other hand, nobody has filed this except for me. Up to you!
