### ISSUE TITLE
Mobile Keyboard Suggestions caused IME Errors

### ISSUE THREAD

**Issue by brian-superlist** [superlistapp/super_editor#1333]
## Summary

Accepting a suggestion from a mobile keyboard causes `Exception: Couldn't map an IME position to a document position.` or 

## Scenario 1

  1. Launch Super Editor example app against iOS Simulator (main or stable branch of super_editor, main or stable of flutter)
  2. Create new paragraph
  3. Accept suggestion from keyboard suggestions (words above the keyboard)
  4. Receive an error

### Scenario 1 Video

https://github.com/superlistapp/super_editor/assets/90610075/9adce2ae-bc16-4ff5-9508-525f0beba091

### Scenario 1 Logs

```
Performing hot restart...
Syncing files to device iPhone 14 Pro Max...
Restarted application in 393ms.
flutter: Initializing logger: ExampleApp

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: 'Is'
IME position: TextPosition(offset: 4, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:147:47)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 5, oldText: . Is, selectionAffinity: TextAffinity.downstream, deltaEnd: 4, deltaText:  , deltaStart: 4, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 5, composingBase: -1}]}])
====================================================================================================
```

## Scenario 2

  1. Launch Super Editor example app
  2. Create a new task component
  3. Start typing
  4. Instead of completing the word, accept the suggestion to complete the word
  6. Delete the content
  7. Then try to use suggestions

## Scenario 2 video

https://github.com/superlistapp/super_editor/assets/90610075/d304e929-5d72-4965-8697-a178da16c8bc

## Scenario 2 Logs

```
Performing hot restart...
Syncing files to device iPhone 14 Pro Max...
Restarted application in 377ms.
flutter: Initializing logger: ExampleApp

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Could not handle EditorRequest. DocumentEditor doesn't have a handler that recognizes the request: Instance of 'DeleteUpstreamAtBeginningOfNodeRequest'

When the exception was thrown, this was the stack: 
#0      Editor._findCommandForRequest (package:super_editor/src/core/editor.dart:189:5)
#1      Editor.execute (package:super_editor/src/core/editor.dart:147:23)
#2      TextDeltasDocumentEditor.delete (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:370:14)
#3      TextDeltasDocumentEditor._applyDeletion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:219:5)
#4      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:83:9)
#5      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#6      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#7      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#8      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#12     _invoke2 (dart:ui/hooks.dart:202:13)
#13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#14     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#15     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 1, oldText: . , selectionAffinity: TextAffinity.downstream, deltaEnd: -1, deltaText: , deltaStart: -1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 2, composingBase: -1}, {selectionBase: 1, oldText: . , selectionAffinity: TextAffinity.downstream, deltaEnd: 2, deltaText: , deltaStart: 1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}]}])
====================================================================================================

======== Exception caught by services library ======================================================
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:152:6)
#1      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#2      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#3      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#9      _invoke2 (dart:ui/hooks.dart:202:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 4, oldText: ., selectionAffinity: TextAffinity.downstream, deltaEnd: 1, deltaText:  Is, deltaStart: 1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 4, composingBase: -1}]}])
====================================================================================================

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 4, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:147:47)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 5, oldText: . Is, selectionAffinity: TextAffinity.downstream, deltaEnd: 4, deltaText:  , deltaStart: 4, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 5, composingBase: -1}]}])
====================================================================================================

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 5, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:147:47)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 6, oldText: . Is , selectionAffinity: TextAffinity.downstream, deltaEnd: 5, deltaText: t, deltaStart: 5, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 6, composingBase: -1}]}])
====================================================================================================

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 6, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:147:47)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 7, oldText: . Is t, selectionAffinity: TextAffinity.downstream, deltaEnd: 6, deltaText: h, deltaStart: 6, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 7, composingBase: -1}]}])
====================================================================================================

======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 7, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:147:47)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:79:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:196:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:202:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:745:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 8, oldText: . Is th, selectionAffinity: TextAffinity.downstream, deltaEnd: 7, deltaText: a, deltaStart: 7, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 8, composingBase: -1}]}])
====================================================================================================
```

**Comment by knopp** [comment]
It seems that the problem here is a race condition. When inserting text at the beginning of paragraph, there are two deltas received from iOS:

First:
```
TextEditingDeltaInsertion (TextEditingDeltaInsertion#36664(oldText: '. ', textInserted: The, insertionOffset: 2, selection: TextSelection.collapsed(offset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
```

Second:
```
TextEditingDeltaInsertion (TextEditingDeltaInsertion#40703(oldText: '. The', textInserted: ' ', insertionOffset: 5, selection: TextSelection.collapsed(offset: 6, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
```

The problem is that while handling the first delta, the IME value is adjusted to remove the placeholder ('. '), which is not reflected in the second delta

**Comment by matthew-carroll** [comment]
I believe this is yet another manifestation of an issue that we logged against Flutter a while ago. @angelosilvestre can you please confirm? If so, can you paste that Flutter issue ticket for reference?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you follow up on my comment above?

**Comment by angelosilvestre** [comment]
@matthew-carroll This seems related to https://github.com/flutter/flutter/issues/129061

When accepting a suggestion,  Flutter sends a space insertion in a second delta batch. Because of that our mapping is out of sync.
