### ISSUE TITLE
[SuperEditor][iOS] IME mapping error while dragging floating cursor between paragraphs

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#1449]
### Steps to reproduce

1. Run the example app on iOS
2. Double tap the word "more"
3. Press and hold the spacebar to show the floating cursor
4. Drag the floating cursor to the word "made" in the next paragraph

### Expected results

The selection moves without exceptions

### Actual results

The selection moves as expected, but the following exception is displayed in the console:

```console
Restarted application in 276ms.
flutter: Initializing logger: ExampleApp

════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: 'Ready-made solutions 📦'
IME position: TextPosition(offset: 98, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack:
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:268:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:18)
#2      TextDeltasDocumentEditor._applyNonTextChange (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:232:41)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:85:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:203:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1873:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1762:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:552:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#11     _invoke2 (dart:ui/hooks.dart:345:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:689:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)

call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 98, oldText: Super Editor is a toolkit to help you build document editors, document layouts, text fields, and more., selectionAffinity: TextAffinity.downstream, deltaEnd: -1, deltaText: , deltaStart: -1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 98, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════

```

**Comment by angelosilvestre** [comment]
After investigation, the issue seems to be that Flutter is reporting non-text deltas after `updateFloatingCursor` is called, even if we are not sending anything to the IME.

I don't know if this was always the case, or if it's a result of a recent change.

I filed https://github.com/flutter/flutter/issues/134989
