### ISSUE TITLE
[golden_runner] Fails to run the golden tests

### ISSUE THREAD

**Issue by rutvik110** [superlistapp/super_editor#1479]
## The Issue:

I'm trying to run the golden tests for super editor through the docker image as specified in the tests read me for `golden_runner`. But trying to run a golden test like follow fails with the error mentioned below,

`goldens test --plain-name "mobile_selection_test" test_goldens/editor/mobile `

<details open>
<summary>Error</summary>
<br>

```
building image#0 building with "desktop-linux" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 209B done
#1 DONE 0.0s

#2 [internal] load build definition from golden_tester.Dockerfile
#2 transferring dockerfile: 681B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/ubuntu:latest
#3 DONE 1.0s

#4 [1/8] FROM docker.io/library/ubuntu:latest@sha256:aabed3296a3d45cede1dc866a24476c4d7e093aa806263c27ddaadbdce3c1054
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 39.41kB 0.0s done
#5 DONE 0.0s

#6 https://api.github.com/repos/flutter/flutter/git/refs/heads/master
#6 DONE 0.0s

#7 [4/8] RUN cat /etc/lsb-release
#7 CACHED

#8 [5/8] ADD https://api.github.com/repos/flutter/flutter/git/refs/heads/master ./flutter-latest-master
#8 CACHED

#9 [6/8] RUN git clone https://github.com/flutter/flutter.git /sdks/flutter
#9 CACHED

#10 [2/8] RUN apt update
#10 CACHED

#11 [3/8] RUN apt install -y git curl unzip
#11 CACHED

#12 [7/8] RUN flutter doctor
#12 CACHED

#13 [8/8] COPY ./ /golden_tester
#13 CACHED

#14 exporting to image
#14 exporting layers done
#14 writing image sha256:15a098270e3e2e9803d197c6b3a6ea9da43a64a6eb1554b611dc20d8ebf665fe done
#14 naming to docker.io/library/supereditor_golden_tester done
#14 DONE 0.0s

Running golden tests
Unhandled exception:
Bad state: StreamSink is already bound to a stream
#0      _StreamSinkImpl.addStream (dart:io/io_sink.dart:166:7)
#1      _StdSink.addStream (dart:io/stdio.dart:361:55)
#2      _runProcess (package:golden_runner/src/commands.dart:322:10)
<asynchronous suspension>
#3      GoldenTestCommand.run (package:golden_runner/src/commands.dart:98:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      main (file:///Users/rutviktak/flutter_projects/mc/super_editor/golden_runner/bin/goldens.dart:13:5)
<asynchronous suspension>
```
</details>

## **To reproduce:**

1. Run any of the golden tests for super editor, for e.g.
`goldens test --plain-name "mobile_selection_test" test_goldens/editor/mobile`

<details open>
<summary>Flutter doctor</summary>
<br>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.15.0-13.0.pre.28, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

<details>

**Comment by matthew-carroll** [comment]
@angelosilvestre do you recognize this error?

**Comment by angelosilvestre** [comment]
I'll take a look.
