### ISSUE TITLE
[SuperEditor] Scrolling on Android in a CustomScrollView creates selection when it shouldn't

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1535]
I'm unable to scroll a document on Android in a CustomScrollView without the keyboard coming up with selection. I've tested this in my own app (running super_editor stable / Flutter stable) as well as the `sliver_example_editor` in the example app (running super_editor stable / Flutter stable). Here's a demo:

https://github.com/superlistapp/super_editor/assets/6467808/6edf3555-3874-4ada-b876-5222eac398f9

I didn't catch this when pushing our app to production yesterday.

cc @matthew-carroll

**Comment by Jethro87** [comment]
@angelosilvestre This is still happening quite regularly in my app and the example app.

https://github.com/superlistapp/super_editor/assets/6467808/b1f70c2e-2616-4032-afdf-202bb8a5c225

I'm also periodically getting this error:

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      _AndroidDocumentTouchInteractorState._onLongPressEnd
document_gestures_touch_android.dart:850
#1      _AndroidDocumentTouchInteractorState._onPanCancel
document_gestures_touch_android.dart:832
#2      GestureRecognizer.invokeCallback
recognizer.dart:275
#3      DragGestureRecognizer._checkCancel
monodrag.dart:579
#4      DragGestureRecognizer.didStopTrackingLastPointer
monodrag.dart:449
#5      OneSequenceGestureRecognizer.stopTrackingPointer
recognizer.dart:465
#6      DragGestureRecognizer._giveUpPointer
monodrag.dart:461
#7      DragGestureRecognizer.rejectGesture
monodrag.dart:437
#8      GestureArenaManager._resolveInFavorOf
arena.dart:278
#9      GestureArenaManager._resolve
arena.dart:239
#10     GestureArenaEntry.resolve
arena.dart:53
#11     OneSequenceGestureRecognizer.resolve
recognizer.dart:375
#12     DragGestureRecognizer.handleEvent
monodrag.dart:414
#13     PointerRouter._dispatch
pointer_router.dart:98
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#16     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#17     PointerRouter.route
pointer_router.dart:127
#18     GestureBinding.handleEvent
binding.dart:488
#19     GestureBinding.dispatchEvent
binding.dart:468
#20     RendererBinding.dispatchEvent
binding.dart:333
#21     GestureBinding._handlePointerEventImmediately
binding.dart:413
#22     GestureBinding.handlePointerEvent
binding.dart:376
#23     GestureBinding._flushPointerEventQueue
binding.dart:323
#24     GestureBinding._handlePointerDataPacket
binding.dart:292
#25     _invoke1 (dart:ui/hooks.dart:186:13)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
Handler: "onCancel"
Recognizer: PanGestureRecognizer#b4417
    start behavior: start
════════════════════════════════════════════════════════════════════════════════
```
