### ISSUE TITLE
[SuperEditor] [iOS] Composing Korean character the start of node throws

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1828]
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/2cb93e23ba2442e911c1bfcaf107c247adc6d131

**To Reproduce**
1. Go to "Empty Document" demo
2. Place the selection in the editor
3. Type "ㅅㅛ" 

**Actual behavior**
Exception is thrown:
```
======== Exception caught by services library ======================================================
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:153:6)
#1      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:80:9)
#2      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:219:30)
#3      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:63)
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1759:20)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [3, {deltas: [{selectionBase: 1, oldText: . ㅅ, selectionAffinity: TextAffinity.downstream, deltaEnd: -1, deltaText: , deltaStart: -1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 3, composingBase: -1}, {selectionBase: 1, oldText: . ㅅ, selectionAffinity: TextAffinity.downstream, deltaEnd: 3, deltaText: , deltaStart: 1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}, {selectionBase: 2, oldText: ., selectionAffinity: TextAffinity.downstream, deltaEnd: 1, deltaText:  , deltaStart: 1, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 2, composingBase: -1}, {selectionBase: 3, oldText: . , selectionAffinity: TextAffinity.downstream, deltaEnd: 2, deltaText: 쇼, deltaStart: 2, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 3, composingBase: -1}]}])
====================================================================================================
```

<details>
<summary>IME logs</summary>

```
flutter: (18.162) editor.ime > FINE: Received edit deltas from platform: 1 deltas
flutter: (18.162) editor.ime > FINE: TextEditingDeltaInsertion#07448(oldText: ., textInserted: ㅅ, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.162) editor.ime > FINE: IME value before applying deltas: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.163) editor.ime > FINE: ===================================================
flutter: (18.163) editor.ime > INFO: Applying 1 IME deltas to document
flutter: (18.163) editor.ime.deltas > FINE: Incoming deltas:
flutter: (18.163) editor.ime.deltas > FINE: Incoming deltas:
flutter: (18.163) editor.ime.deltas > FINE: TextEditingDeltaInsertion#07448(oldText: ., textInserted: ㅅ, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.163) editor.ime.deltas > FINE: TextEditingDeltaInsertion#07448(oldText: ., textInserted: ㅅ, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.164) editor.ime > FINE: Serializing document to perform IME operations
flutter: (18.164) editor.ime > FINE: Creating an IME model from document, selection, and composing region
flutter: (18.165) editor.ime > FINE: IME serialization:
'. '
flutter: (18.165) editor.ime > FINE: Converting doc selection to ime selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream)))
flutter: (18.165) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (18.165) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (18.165) editor.ime > FINE: Start IME position: TextPosition(offset: 2, affinity: TextAffinity.downstream)
flutter: (18.165) editor.ime > FINE: End IME position: TextPosition(offset: 2, affinity: TextAffinity.downstream)
flutter: (18.165) editor.ime > FINE: Converting doc range to ime range: null
flutter: (18.165) editor.ime > FINE: The document range is null. Returning an empty IME range.
flutter: (18.165) editor.ime > INFO: ---------------------------------------------------
flutter: (18.166) editor.ime > INFO: Applying delta: TextEditingDeltaInsertion#07448(oldText: ., textInserted: ㅅ, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.166) editor.ime > FINE: Inserted text: "ㅅ"
flutter: (18.166) editor.ime > FINE: Insertion offset: 2
flutter: (18.166) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (18.166) editor.ime > FINE: Composing: TextRange(start: -1, end: -1)
flutter: (18.166) editor.ime > FINE: Old text: ". "
flutter: (18.167) editor.ime > FINE: Inserting text: 'ㅅ', at insertion offset: 2, with ime selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (18.167) editor.ime > FINE: Converting IME insertion offset into a DocumentSelection
flutter: (18.167) editor.ime > FINE: Creating doc selection from IME selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (18.167) editor.ime > FINE: The IME only selected visible characters. No adjustment necessary.
flutter: (18.168) editor.ime > FINE: Calculating the base DocumentPosition for the DocumentSelection
flutter: (18.168) editor.ime > FINE: Selection base: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (18.168) editor.ime > FINE: Calculating the extent DocumentPosition for the DocumentSelection
flutter: (18.168) editor.ime > FINE: Selection extent: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (18.168) editor.ime > FINE: Inserting "ㅅ" at position "[DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream)))"
flutter: (18.168) editor.ime > FINE: Updating the Document Composer's selection to place caret at insertion offset:
[DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream)))
flutter: (18.169) editor.ime > FINE: Inserting the text at the Document Composer's selection
flutter: (18.170) editor.ime > FINE: Insertion successful? true
flutter: (18.170) editor.ime > FINE: Creating an IME model from document, selection, and composing region
flutter: (18.171) editor.ime > FINE: IME serialization:
'. ㅅ'
flutter: (18.171) editor.ime > FINE: Creating doc range from IME range: TextRange(start: -1, end: -1)
flutter: (18.171) editor.ime > FINE: The IME range is empty. Returning null document range.
flutter: (18.171) editor.ime > INFO: ---------------------------------------------------
flutter: (18.171) editor.ime > FINE: After applying all deltas, converting the final composing region to a document range.
flutter: (18.172) editor.ime > FINE: Raw IME delta composing region: TextRange(start: -1, end: -1)
flutter: (18.172) editor.ime > FINE: Creating doc range from IME range: TextRange(start: -1, end: -1)
flutter: (18.172) editor.ime > FINE: The IME range is empty. Returning null document range.
flutter: (18.172) editor.ime > FINE: Document composing region: null
flutter: (18.172) editor.ime > FINE: ===================================================
flutter: (18.172) editor.ime > FINE: [DocumentImeInputClient] - Serializing and sending document and selection to IME
flutter: (18.172) editor.ime > FINE: [DocumentImeInputClient] - Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
flutter: (18.173) editor.ime > FINE: [DocumentImeInputClient] - Composing region: null
flutter: (18.173) editor.ime > FINE: Creating an IME model from document, selection, and composing region
flutter: (18.173) editor.ime > FINE: IME serialization:
'. ㅅ'
flutter: (18.173) editor.ime > FINE: [DocumentImeInputClient] - Adding invisible characters?: true
flutter: (18.173) editor.ime > FINE: Creating TextEditingValue from document. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
flutter: (18.173) editor.ime > FINE: Text:
'. ㅅ'
flutter: (18.173) editor.ime > FINE: Converting doc selection to ime selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
flutter: (18.174) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (18.174) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (18.174) editor.ime > FINE: Start IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)
flutter: (18.174) editor.ime > FINE: End IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)
flutter: (18.174) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (18.175) editor.ime > FINE: Converting doc range to ime range: null
flutter: (18.175) editor.ime > FINE: The document range is null. Returning an empty IME range.
flutter: (18.175) editor.ime > FINE: Composing region: TextRange(start: -1, end: -1)
flutter: (18.175) editor.ime > FINE: [DocumentImeInputClient] - Sending IME serialization:
flutter: (18.175) editor.ime > FINE: [DocumentImeInputClient] - TextEditingValue(text: ┤. ㅅ├, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.175) editor.ime > FINE: Wants to send a value to IME: TextEditingValue(text: ┤. ㅅ├, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.175) editor.ime > FINE: The current local IME value: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.175) editor.ime > FINE: The current platform IME value: TextEditingValue(text: ┤. ├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.176) editor.ime > FINE: Ignoring new TextEditingValue because it's the same as the existing one: TextEditingValue(text: ┤. ㅅ├, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (18.176) editor.ime > FINE: [DocumentImeInputClient] - Done sending document to IME
flutter: (20.040) editor.ime > FINE: Received edit deltas from platform: 4 deltas
flutter: (20.041) editor.ime > FINE: TextEditingDeltaNonTextUpdate#3c92c(oldText: . ㅅ, selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.041) editor.ime > FINE: TextEditingDeltaDeletion#6c44f(oldText: . ㅅ, textDeleted:  ㅅ, deletedRange: TextRange(start: 1, end: 3), selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.041) editor.ime > FINE: TextEditingDeltaInsertion#06a43(oldText: ., textInserted:, insertionOffset: 1, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.041) editor.ime > FINE: TextEditingDeltaInsertion#9148f(oldText: ., textInserted: 쇼, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.041) editor.ime > FINE: IME value before applying deltas: TextEditingValue(text: ┤. ㅅ├, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.041) editor.ime > FINE: ===================================================
flutter: (20.041) editor.ime > INFO: Applying 4 IME deltas to document
flutter: (20.042) editor.ime.deltas > FINE: Incoming deltas:
flutter: (20.042) editor.ime.deltas > FINE: Incoming deltas:
flutter: (20.042) editor.ime.deltas > FINE: TextEditingDeltaNonTextUpdate#3c92c(oldText: . ㅅ, selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.042) editor.ime.deltas > FINE: TextEditingDeltaNonTextUpdate#3c92c(oldText: . ㅅ, selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.042) editor.ime.deltas > FINE: TextEditingDeltaDeletion#6c44f(oldText: . ㅅ, textDeleted:  ㅅ, deletedRange: TextRange(start: 1, end: 3), selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.042) editor.ime.deltas > FINE: TextEditingDeltaDeletion#6c44f(oldText: . ㅅ, textDeleted:  ㅅ, deletedRange: TextRange(start: 1, end: 3), selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.043) editor.ime.deltas > FINE: TextEditingDeltaInsertion#06a43(oldText: ., textInserted:, insertionOffset: 1, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.043) editor.ime.deltas > FINE: TextEditingDeltaInsertion#06a43(oldText: ., textInserted:, insertionOffset: 1, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.043) editor.ime.deltas > FINE: TextEditingDeltaInsertion#9148f(oldText: ., textInserted: 쇼, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.043) editor.ime.deltas > FINE: TextEditingDeltaInsertion#9148f(oldText: ., textInserted: 쇼, insertionOffset: 2, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.044) editor.ime > FINE: Serializing document to perform IME operations
flutter: (20.044) editor.ime > FINE: Creating an IME model from document, selection, and composing region
flutter: (20.044) editor.ime > FINE: IME serialization:
'. ㅅ'
flutter: (20.045) editor.ime > FINE: Converting doc selection to ime selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
flutter: (20.045) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (20.045) editor.ime > FINE: Converting DocumentPosition to IME TextPosition: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (20.045) editor.ime > FINE: Start IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)
flutter: (20.045) editor.ime > FINE: End IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)
flutter: (20.045) editor.ime > FINE: Converting doc range to ime range: null
flutter: (20.045) editor.ime > FINE: The document range is null. Returning an empty IME range.
flutter: (20.045) editor.ime > INFO: ---------------------------------------------------
flutter: (20.045) editor.ime > INFO: Applying delta: TextEditingDeltaNonTextUpdate#3c92c(oldText: . ㅅ, selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.046) editor.ime > FINE: Non-text change:
flutter: (20.046) editor.ime > FINE: OS-side selection - TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false)
flutter: (20.046) editor.ime > FINE: OS-side composing - TextRange(start: -1, end: -1)
flutter: (20.046) editor.ime > FINE: Creating doc selection from IME selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false)
flutter: (20.046) editor.ime > FINE: Removing invisible characters from IME selection.
flutter: (20.046) editor.ime > FINE: Adjusted IME selection is: TextSelection(baseOffset: 2, extentOffset: 3, isDirectional: false)
flutter: (20.046) editor.ime > FINE: Calculating the base DocumentPosition for the DocumentSelection
flutter: (20.046) editor.ime > FINE: Selection base: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (20.046) editor.ime > FINE: Calculating the extent DocumentPosition for the DocumentSelection
flutter: (20.047) editor.ime > FINE: Selection extent: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (20.047) editor.ime > FINE: Creating doc range from IME range: TextRange(start: -1, end: -1)
flutter: (20.047) editor.ime > FINE: The IME range is empty. Returning null document range.
flutter: (20.048) editor.ime > INFO: ---------------------------------------------------
flutter: (20.048) editor.ime > INFO: ---------------------------------------------------
flutter: (20.048) editor.ime > INFO: Applying delta: TextEditingDeltaDeletion#6c44f(oldText: . ㅅ, textDeleted:  ㅅ, deletedRange: TextRange(start: 1, end: 3), selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.048) editor.ime > FINE: Delete delta:
Text deleted: ' ㅅ'
Deleted Range: TextRange(start: 1, end: 3)
Selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false)
Composing: TextRange(start: -1, end: -1)
Old text: '. ㅅ'
flutter: (20.048) editor.ime > FINE: Creating doc selection from IME selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false)
flutter: (20.048) editor.ime > FINE: Removing invisible characters from IME selection.
flutter: (20.048) editor.ime > FINE: Adjusted IME selection is: TextSelection(baseOffset: 2, extentOffset: 3, isDirectional: false)
flutter: (20.049) editor.ime > FINE: Calculating the base DocumentPosition for the DocumentSelection
flutter: (20.049) editor.ime > FINE: Selection base: [DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))
flutter: (20.049) editor.ime > FINE: Calculating the extent DocumentPosition for the DocumentSelection
flutter: (20.049) editor.ime > FINE: Selection extent: [DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream))
flutter: (20.049) editor.ime > FINE: Doc selection to delete: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "1", position: (TextPosition(offset: 1, affinity: TextAffinity.downstream)))
flutter: (20.049) editor.ime > FINE: Running selection deletion operation
flutter: (20.050) editor.ime > FINE: Deletion operation complete
flutter: (20.051) editor.ime > INFO: ---------------------------------------------------
flutter: (20.051) editor.ime > INFO: ---------------------------------------------------
flutter: (20.051) editor.ime > INFO: Applying delta: TextEditingDeltaInsertion#06a43(oldText: ., textInserted:, insertionOffset: 1, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
flutter: (20.051) editor.ime > FINE: Inserted text: " "
flutter: (20.051) editor.ime > FINE: Insertion offset: 1
flutter: (20.051) editor.ime > FINE: Selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (20.051) editor.ime > FINE: Composing: TextRange(start: -1, end: -1)
flutter: (20.051) editor.ime > FINE: Old text: "."
flutter: (20.051) editor.ime > FINE: Inserting text: ' ', at insertion offset: 1, with ime selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (20.051) editor.ime > FINE: Converting IME insertion offset into a DocumentSelection
flutter: (20.052) editor.ime > FINE: Creating doc selection from IME selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false)
flutter: (20.052) editor.ime > FINE: The IME only selected invisible characters. Returning a null document selection.
```
</details>

**Expected behavior**
"ㅅㅛ" gets converted to "쇼".

**Platform**
iOS for sure, but did not manage to test it on Android yet. Does not happen on macOS.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Comment by miguelcmedeiros** [comment]
@angelosilvestre from https://github.com/superlistapp/super_editor/issues/1825 we learned that the iOS simulator is buggy when it comes to Korean, i.e. it does not compose as you type.

I can only reproduce this on a real iOS device and I just use a Korean keyboard layout without any special setting.

**Comment by angelosilvestre** [comment]
@miguelcmedeiros Thanks for the clarification. I'll try this with a real iOS device later today.

**Comment by angelosilvestre** [comment]
@matthew-carroll This issue is caused by unexpected deltas generated by the IME. Upon typing "ㅅㅛ" the following batches of deltas are generated:

First batch:

```dart
[
  TextEditingDeltaInsertion(
    oldText: '. ',
    textInserted: 'ㅅ',
    insertionOffset: 2,
    selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream),
    composing: TextRange(start: -1, end: -1),
  ),
]
```

Second batch:

```dart
[
  TextEditingDeltaNonTextUpdate(
    oldText: '. ㅅ',
    selection: TextSelection(baseOffset: 1, extentOffset: 3, isDirectional: false),
    composing: TextRange(start: -1, end: -1),
  ),
  TextEditingDeltaDeletion(
    oldText: '. ㅅ',
    deletedRange: TextRange(start: 1, end: 3),
    selection: TextSelection.collapsed(
      offset: 1,
      affinity: TextAffinity.downstream,
    ),
    composing: TextRange(start: -1, end: -1),
  ),
  TextEditingDeltaInsertion(
    oldText: '.',
    textInserted: ' ',
    insertionOffset: 1,
    selection: TextSelection.collapsed(
      offset: 2,
      affinity: TextAffinity.downstream,
    ),
    composing: TextRange(start: -1, end: -1),
  ),
  TextEditingDeltaInsertion(
    oldText: '. ',
    textInserted: '쇼',
    insertionOffset: 2,
    selection: TextSelection.collapsed(
      offset: 3,
      affinity: TextAffinity.downstream,
    ),
    composing: TextRange(start: -1, end: -1),
  )
]
```

The second and third deltas are unexpected. First, the IME is deleting the range `TextRange(start: 1, end: 3)`, which includes the space that is part of the invisible characters. Then, it inserts the space back. Since this insertion has an invalid offset (it happens on an "invisible" offset) we crash when we try to compute the insertion selection.

Should we file a Flutter ticket for this? Should we try to work around this?

**Comment by matthew-carroll** [comment]
@angelosilvestre we should do both. Let's file an issue and then let's work around this.

**Comment by angelosilvestre** [comment]
Filed https://github.com/flutter/flutter/issues/142894

**Comment by matthew-carroll** [comment]
@angelosilvestre did you happen to check this behavior on Android to see if it happens there too?

**Comment by angelosilvestre** [comment]
@matthew-carroll I tested it and it doesn't happen on Android.
