### ISSUE TITLE
Scrolling with magic mouse doesn't work properly

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#1946]
`DocumentMouseInteractor` calls `cancelScrollMomentum` on mouse move, which stops scrolling, but with magic mouse it is possible (and normal) to move mouse. I don't really understand the intent behind reimplementing scrolling this way, but IIRC there is `PointerScrollInertiaCancelEvent` which would normally signal when the scrolling need to stop.

**Comment by knopp** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at the referenced code and see if you remember why we did what we did? We've worked around so many Flutter holes at this point that I don't recall off the top of my head.

**Comment by angelosilvestre** [comment]
@matthew-carroll We probably used this before `PointerScrollInertiaCancelEvent`. I think we started cancelling the momentum on mouse move when Flutter introduced some changes in this area.

Currently, even without us handling `PointerScrollInertiaCancelEvent` in `SuperEditor` code, touching the trackpad already stops the momentum, because `Scrollable` cancels the momentum when it receives a `PointerScrollInertiaCancelEvent`:

```dart
void _receivedPointerSignal(PointerSignalEvent event) {
    if (event is PointerScrollEvent && _position != null) {
      if (_physics != null && !_physics!.shouldAcceptUserOffset(position)) {
        return;
      }
      final double delta = _pointerSignalEventDelta(event);
      final double targetScrollOffset = _targetScrollOffsetForPointerScroll(delta);
      // Only express interest in the event if it would actually result in a scroll.
      if (delta != 0.0 && targetScrollOffset != position.pixels) {
        GestureBinding.instance.pointerSignalResolver.register(event, _handlePointerScroll);
      }
    } else if (event is PointerScrollInertiaCancelEvent) {
      position.pointerScroll(0);  <--- This line
      // Don't use the pointer signal resolver, all hit-tested scrollables should stop.
    }
  }
```

Stack trace:
```
#0      ScrollPositionWithSingleContext.goIdle (package:flutter/src/widgets/scroll_position_with_single_context.dart:130:22)
#1      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:154:7)
#2      ScrollPositionWithSingleContext.pointerScroll (package:flutter/src/widgets/scroll_position_with_single_context.dart:218:7)
#3      ScrollableState._receivedPointerSignal (package:flutter/src/widgets/scrollable.dart:915:16)
#4      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3099:31)
#5      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#11     _invoke1 (dart:ui/hooks.dart:328:13)
#12     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#13     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```

I think we should be good by just removing our `_cancelScrollMomentum` call.

**Comment by matthew-carroll** [comment]
@angelosilvestre  - Ok, can you please take care of that?
