### ISSUE TITLE
[SuperEditor] Toggling attribution throws 

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1948]
**Package Version**
Using `main` branch with commit e083e6bb550892785e6bccd5a7a33a51ed462850.

**To Reproduce**
1. Go to SuperEditor demo
2. Place the selection at the end of a text node and expand the selection to the content of the next text node
3. Press CMD+B twice

**Actual behavior**
Text is made bold and then turned to normal.

**Expected behavior**
Text is made bold, but an exception is thrown and the editor is left in a broken state:
```
======== Exception caught by services library ======================================================
The following _Exception was thrown while processing the key message handler:
Exception: removeAttribution() did not satisfy start < 0 and start > end, start: 70, end: 69

When the exception was thrown, this was the stack: 
#0      AttributedSpans.removeAttribution (package:attributed_text/src/attributed_spans.dart:422:7)
#1      AttributedText.removeAttribution (package:attributed_text/src/attributed_text.dart:189:11)
#2      ToggleTextAttributionsCommand.execute (package:super_editor/src/default_editor/text.dart:1526:14)
#3      _DocumentEditorCommandExecutor.executeCommand (package:super_editor/src/core/editor.dart:252:15)
#4      Editor._executeCommand (package:super_editor/src/core/editor.dart:195:22)
#5      Editor.execute (package:super_editor/src/core/editor.dart:148:30)
#6      CommonEditorOperations.toggleAttributionsOnSelection (package:super_editor/src/default_editor/common_editor_operations.dart:1466:12)
#7      cmdBToToggleBold (package:super_editor/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:337:27)
#8      _SuperEditorHardwareKeyHandlerState._onKeyPressed (package:super_editor/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart:84:50)
#9      _HighlightModeManager.handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:2069:29)
#10     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1099:34)
#11     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1171:17)
#12     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:576:35)
#14     _invoke2 (dart:ui/hooks.dart:344:13)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
KeyMessage: KeyMessage([KeyDownEvent#ae18e(physicalKey: PhysicalKeyboardKey#7e294(usbHidUsage: "0x00070005", debugName: "Key B"), logicalKey: LogicalKeyboardKey#15902(keyId: "0x00000062", keyLabel: "B", debugName: "Key B"), character: "b", timeStamp: 1474:27:27.470860)])
====================================================================================================
```

**Platform**
MacOS

**Flutter version**
Master channel with commit b9e9435b25c45c41314979c06115373cc811ce1d.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/f08bc48a-50ab-46ba-af45-7004c57ace8d

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre
