### ISSUE TITLE
Android interactor assumes an offset will map to a document position

### ISSUE THREAD

**Issue by jellynoone** [superlistapp/super_editor#2001]
**Package Version**
`stable`

**To Reproduce**
1. Run the code below on Android
2. Click on text
3. Attempt to scroll by dragging the horizontal white space

**Minimal Reproduction Code**
<details>
  <summary>Minimal, Runnable Code Sample</summary>

  ```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final _document = MutableDocument(nodes: [
    for (var i = 0; i < 2; i++)
      ParagraphNode(
        id: Editor.createNodeId(),
        text: AttributedText('Some random text.'),
      ),
  ]);
  final _composer = MutableDocumentComposer();
  late final _editor = createDefaultDocumentEditor(
    composer: _composer,
    document: _document,
  );

  @override
  void dispose() {
    _editor.dispose();
    _document.dispose();
    _composer.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SuperEditor(
            stylesheet: Stylesheet(
              rules: defaultStylesheet.rules,
              documentPadding: EdgeInsets.symmetric(horizontal: 100),
              selectedTextColorStrategy:
                  defaultStylesheet.selectedTextColorStrategy,
              inlineTextStyler: defaultStylesheet.inlineTextStyler,
            ),
            editor: _editor,
            document: _document,
            composer: _composer,
          ),
        ),
      ),
    );
  }
}

  ```
</details>

**Actual behavior**
An error occurs due to the pointer offset not mapping to any document position and the interactor assuming it does.
The error happens at: https://github.com/superlistapp/super_editor/blob/ced4413f515525cc422c2072172e2bc332069152/super_editor/lib/src/default_editor/document_gestures_touch_android.dart#L981

**Expected behavior**
There should be no error.

**Platform**
Android

**Flutter version**
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (5 days ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3

**Comment by matthew-carroll** [comment]
@jellynoone please be sure to include the stacktrace for the actual error when you file a bug ticket.

**Comment by jellynoone** [comment]
<details>
<summary>Exception</summary>

```txt
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _AndroidDocumentTouchInteractorState._onPanStart (package:super_editor/src/default_editor/document_gestures_touch_android.dart:981:100)
document_gestures_touch_android.dart:981
#1      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:787:53)
monodrag.dart:787
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
recognizer.dart:344
#3      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:787:7)
monodrag.dart:787
#4      DragGestureRecognizer._checkDrag (package:flutter/src/gestures/monodrag.dart:754:5)
monodrag.dart:754
#5      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:681:7)
monodrag.dart:681
#6      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:269:25)
arena.dart:269
#7      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:249:31)
arena.dart:249
(elided 2 frames from dart:async)

Handler: "onStart"
Recognizer: VerticalDragGestureRecognizer#d35ab
    start behavior: down
```
</details>
