### ISSUE TITLE
[SuperEditor][iOS] - IME to document mapping error when inserting new paragraph

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#2007]
**Package Version**
main branch

**To Reproduce**
1. Run super editor demo
2. Place the caret at the end of a paragraph and press "return" on the software keyboard to start a new one
3. Type "run tom"
4. Press "return" again to start another paragraph

**Actual behavior**
An error is reported to the console

**Expected behavior**
No error is reported

**Platform**
iOS - 17.5, 17.4, 17.2

**Flutter version**
master

**Error Log**
```
======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. '
IME position: TextPosition(offset: 6, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:309:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:166:18)
#2      TextDeltasDocumentEditor.replace (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:360:49)
#3      TextDeltasDocumentEditor._applyReplacement (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:220:5)
#4      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:83:9)
#5      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:219:30)
#6      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#7      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1904:63)
#8      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1795:20)
#9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:597:35)
#12     _invoke2 (dart:ui/hooks.dart:344:13)
#13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#14     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#15     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 9, oldText: . Run tom, selectionAffinity: TextAffinity.downstream, deltaEnd: 9, deltaText: Tom, deltaStart: 6, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 9, composingBase: -1}]}])
====================================================================================================
```

**Comment by angelosilvestre** [comment]
For the record, this is a timing issue. This is what happens:

- The current editing value is "run tom"
- The user presses the new line button
- We receive the a `TextInputAction.newline`
- SuperEditor handles this action, adds a new paragraph, and sends `. ` as the new editing text
- We receive a replacement delta from the IME, replacing "run tom" with "run Tom". Since our editing value is already `. `, the offsets reported in the delta are invalid for us, causing the crash.
- We receive a `\n` insertion from the IME.
