### ISSUE TITLE
[SuperEditor] ~~ throws an exception

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#2028]
**Package Version**
Running on main with commit 77d5177d2e9dad12c7588cfdd067f5454550a7c7.

**To Reproduce**
1. Go to SuperEditor demo
2. Type ~~

**Actual behavior**
An exception is thrown and the editor becomes unresponsive:
```
======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '. I want to make this ~~'
IME position: TextPosition(offset: 23, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:309:5)
#1      DocumentImeSerializer.imeToDocumentRange (package:super_editor/src/default_editor/document_ime/document_serialization.dart:218:14)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:187:53)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:81:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:232:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1903:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1794:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:576:35)
#11     _invoke2 (dart:ui/hooks.dart:344:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [3, {deltas: [{selectionBase: 24, oldText: . I want to make this ~, selectionAffinity: TextAffinity.downstream, deltaEnd: 23, deltaText: ~, deltaStart: 23, composingExtent: 24, selectionIsDirectional: false, selectionExtent: 24, composingBase: 23}]}])
====================================================================================================
```

**Expected behavior**
There's no exception.

**Platform**
All platforms

**Flutter version**
Master channel with commit d5bcd587aa72570faf12875bdfb326ab51eba961.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll
