### ISSUE TITLE
[SuperEditor] Editor crashes when user types [google](www.google.com)

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#2074]
**Package Version**
main

**To Reproduce**
1. Go to SuperEditor demo
2. On a paragraph write `[google](www.google.com)`

**Actual behavior**
Throws an exception:
```
The following FormatException was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Missing end `]` to match `[` in host (at character 9)
https://[google](www.goggle.com)
        ^

When the exception was thrown, this was the stack: 
#0      _Uri._fail (dart:core/uri.dart:1737:5)
#1      _Uri._makeHost (dart:core/uri.dart:2068:9)
#2      new _Uri.notSimple (dart:core/uri.dart:1612:14)
#3      Uri.parse (dart:core/uri.dart:1138:17)
#4      parseLink (package:super_editor/src/default_editor/default_document_editor_reactions.dart:848:13)
#5      LinkifyReaction._extractUpstreamWordAndLinkify (package:super_editor/src/default_editor/default_document_editor_reactions.dart:667:19)
#6      LinkifyReaction.react (package:super_editor/src/default_editor/default_document_editor_reactions.dart:610:9)
#7      Editor._reactToChanges (package:super_editor/src/core/editor.dart:218:16)
#8      Editor.execute (package:super_editor/src/core/editor.dart:161:9)
#9      TextDeltasDocumentEditor._insertPlainText (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:333:12)
#10     TextDeltasDocumentEditor.insert (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:285:23)
#11     TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:175:5)
#12     TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:81:9)
#13     DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:232:30)
#14     DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#15     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1903:63)
#16     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1794:20)
#17     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#18     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#19     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:576:35)
#20     _invoke2 (dart:ui/hooks.dart:344:13)
#21     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#22     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#23     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#24     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#25     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 27, oldText: . [google](www.goggle.com), selectionAffinity: TextAffinity.downstream, deltaEnd: 26, deltaText:  , deltaStart: 26, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 27, composingBase: -1}]}])
```

**Expected behavior**
Ideally it should linkify the word "google". 
The very least, it should not crash the browser.

**Platform**
All.

**Flutter version**
Flutter master

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre
