### ISSUE TITLE
Ticker started twice exception

### ISSUE THREAD

**Issue by cenomla** [superlistapp/super_editor#245]
I have a use case where I embed the super editor inside a widget that is resized by the user. When the resize happens I encounter the following exception:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A ticker was started twice.
A ticker that is already active cannot be started again without first stopping it.
The affected ticker was:
  Ticker(created by _DocumentInteractorState#795b4)
  The stack trace when the Ticker was actually created was:
  #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
  #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
  #2      SingleTickerProviderStateMixin.createTicker
  (package:flutter/src/widgets/ticker_provider.dart:129:15)
  #3      _DocumentInteractorState.initState
  (package:super_editor/src/default_editor/document_interaction.dart:98:15)
  #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4770:57)
  #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4605:5)
  ...     Normal element mounting (26 frames)
  #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3662:14)
  #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3411:20)
  #33     _LayoutBuilderElement._layout.<anonymous closure>
  (package:flutter/src/widgets/layout_builder.dart:140:18)
  #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2572:19)
  #35     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:122:12)
  #36     RenderObject.invokeLayoutCallback.<anonymous closure>
  (package:flutter/src/rendering/object.dart:1898:59)
  #37     PipelineOwner._enableMutationsToDirtySubtrees
  (package:flutter/src/rendering/object.dart:912:15)
  #38     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1898:14)
  #39     RenderConstrainedLayoutBuilder.rebuildIfNecessary
  (package:flutter/src/widgets/layout_builder.dart:229:7)
  #40     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:364:5)
  #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1788:7)
  #42     _RenderLayoutBuilder.performLayout
  (package:flutter/src/widgets/layout_builder.dart:366:14)
  #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1644:7)
  #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
  #45     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
  #46     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:879:13)
  #47     RendererBinding._handlePersistentFrameCallback
  (package:flutter/src/rendering/binding.dart:328:5)
  #48     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
  #49     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
  #50     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
  #54     _invoke (dart:ui/hooks.dart:163:10)
  #55     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
  #56     _drawFrame (dart:ui/hooks.dart:126:31)
  (elided 3 frames from dart:async)

When the exception was thrown, this was the stack:
#0      Ticker.start.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:151:9)
#1      Ticker.start (package:flutter/src/scheduler/ticker.dart:158:6)
#2      _DocumentInteractorState._startScrollingDown
(package:super_editor/src/default_editor/document_interaction.dart:570:13)
#3      _DocumentInteractorState._scrollIfNearBoundary
(package:super_editor/src/default_editor/document_interaction.dart:522:7)
#4      _DocumentInteractorState._onPanUpdate.<anonymous closure>
(package:super_editor/src/default_editor/document_interaction.dart:323:7)
#5      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
#6      _DocumentInteractorState._onPanUpdate
(package:super_editor/src/default_editor/document_interaction.dart:315:5)
#7      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#9      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
#10     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:139:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:182:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)

Handler: "onUpdate"
Recognizer:
  PanGestureRecognizer#f43fe
════════════════════════════════════════════════════════════════════════════════════════════════════
```
It seems like a race condition where the editor isn't expecting to be rebuilt inside of a gesture handler. A workaround or fix for this would be much appreciated.

I am able to reproduce using commit `7438b7e3508b7b16d1e63f282d311f9796ca77c4`

**Comment by matthew-carroll** [comment]
@cenomla can you provide a minimal project or minimal code that reproduces this issue?
