### ISSUE TITLE
Hash map exception thrown when applying a toggle text attribution command using custom attributions

### ISSUE THREAD

**Issue by cenomla** [superlistapp/super_editor#246]
I have a demo where I toggle some custom color attributions with the following code:
```
_editor.executeCommand(ToggleTextAttributionsCommand(
  documentSelection: selection,
  attributions: attributeToggles,
));
```

If I try and toggle attributes on text that already has some attributes I get the following exception:
```══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following ConcurrentModificationError was thrown while dispatching notifications for
ValueNotifier<TextStyle>:
Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<dynamic>'.

When the exception was thrown, this was the stack:
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:473:7)
#1      AttributedSpans.hasAttributionsWithin (package:super_editor/src/infrastructure/attributed_spans.dart:70:33)
#2      AttributedText.hasAttributionsWithin (package:super_editor/src/infrastructure/attributed_text.dart:56:18)
#3      ToggleTextAttributionsCommand.execute (package:super_editor/src/default_editor/text.dart:792:25)
#4      DocumentEditor.executeCommand (package:super_editor/src/core/document_editor.dart:38:13)
#5      _SuperTextEditorState._toggleStyleForSelection
(package:flutter_folio/styled_widgets/super_text_editor.dart:170:13)
#6      _SuperTextEditorState._handleStyleChanged
(package:flutter_folio/styled_widgets/super_text_editor.dart:180:5)
#7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#9      _NetworkedScrapboardState._handleScrapStyleChanged
(package:flutter_folio/views/editor_page/networked_scrapboard.dart:142:20)
#10     _NetworkedScrapboardState.build.<anonymous closure>.<anonymous closure>
(package:flutter_folio/views/editor_page/networked_scrapboard.dart:77:48)
#11     _ScrapPopupEditorState._handleFgColorChanged
(package:flutter_folio/views/editor_page/scrap_popup_editor/scrap_popup_editor.dart:223:26)
#12     ScrapPopupPanelColor.build.<anonymous closure>.<anonymous closure>
(package:flutter_folio/views/editor_page/scrap_popup_editor/scrap_popup_panel_color.dart:43:57)
#13     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#15     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#16     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#17     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#18     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#29     _invoke1 (dart:ui/hooks.dart:182:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)

The ValueNotifier<TextStyle> sending notification was:
  ValueNotifier<TextStyle>#57e3a(TextStyle(inherit: true, color: Color(0xff29fd2e), backgroundColor:
  Color(0x00000000), family: Caveat, weight: 400, style: normal))
════════════════════════════════════════════════════════════════════════════════════════════════════
```
The color attribution class:
```
class ColorAttribution extends Attribution {
  @override
  String get id => 'color ${background ? "bg" : "fg"}';

  Color color;
  bool background;

  ColorAttribution({this.color = Colors.black, this.background = false});

  @override
  bool canMergeWith(Attribution other) {
    if (other.id == id && (other as ColorAttribution).color == color && other.background == background) {
      return true;
    }
    return false;
  }
}
```
It seems that this also can happen with `NamedAttributions` as well but I don't have a repro for that.

**Comment by matthew-carroll** [comment]
@cenomla can you provide a minimal reproduction of the issue?
