### ISSUE TITLE
Exception thrown when cursor when placing the caret before an emoji

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#391]
Steps to reproduce:
* Paste an emoji into a document (e.g. ❤️)
* Place the caret before the emoji
* Press left-arrow key

Then the following exception is thrown:

```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building BlinkingTextCaret(dirty, state: _BlinkingTextCaretState#a81f5):
Bad state: No element

When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:339:5)
#1      SuperSelectableTextState.getCharacterBox (package:super_editor/src/infrastructure/super_selectable_text.dart:292:10)
#2      SuperSelectableTextState.getLineHeightAtPosition (package:super_editor/src/infrastructure/super_selectable_text.dart:224:12)
#3      _BlinkingTextCaretState.build (package:super_editor/src/infrastructure/caret.dart:40:42)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4716:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5637:32)
#13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6295:17)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5637:32)
#30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6295:17)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2589:33)
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#51     _invoke (dart:ui/hooks.dart:151:10)
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#53     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Comment by matthew-carroll** [comment]
@miguelcmedeiros the problem is that Flutter doesn't give us character boxes for emojis. In fact, Flutter seems to have an issue even giving us a character box for the character that comes after an emoji.

We have two options. Either, we can update all the uses of this query to deal with the otherwise impossible situation of a `null` result, or, we can consider this a Flutter bug and wait for the Flutter team to fix it.

Here's a Dart Pad samples that will print out the character boxes in a `String` with an emoji and you can see exactly what I mean:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final _textKey = GlobalKey();
  
  void _findTextBoxes() {
    final renderParagraph = _textKey.currentContext!.findRenderObject() as RenderParagraph;
    
    print("Char1 boxes: ${_getCharacterBoxes(renderParagraph, 0)}");
    print("Char2 boxes: ${_getCharacterBoxes(renderParagraph, 1)}");
    print("Char3 boxes: ${_getCharacterBoxes(renderParagraph, 2)}");
    print("Char4 boxes: ${_getCharacterBoxes(renderParagraph, 3)}");
    print("Char5 boxes: ${_getCharacterBoxes(renderParagraph, 4)}");
  }
  
  List<TextBox> _getCharacterBoxes(RenderParagraph renderParagraph, int offset) {
    return renderParagraph.getBoxesForSelection(
      TextSelection(baseOffset: offset, extentOffset: offset + 1),
    ).toList();
  }
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(
          textKey: _textKey,
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _findTextBoxes,
          child: const Icon(Icons.text_format),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  const MyWidget({
    Key? key,
    required this.textKey,
  }) : super(key: key);
  
  final GlobalKey textKey;
  
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Text(
      'AB❤️CD',
      key: widget.textKey,
      style: Theme.of(context).textTheme.headline4,
    );
  }
}
```

The output is:
```bash
Char1 boxes: [TextBox.fromLTRBD(0.0, 0.0, 22.2, 39.9, TextDirection.ltr)]
Char2 boxes: [TextBox.fromLTRBD(22.2, 0.0, 43.3, 39.9, TextDirection.ltr)]
Char3 boxes: []
Char4 boxes: []
Char5 boxes: [TextBox.fromLTRBD(85.8, 0.0, 107.9, 39.9, TextDirection.ltr)]
```

**Comment by miguelcmedeiros** [comment]
@matthew-carroll, by playing around with `TextField` and `SelectableText` it seems that Flutter solved/worked around this issue somehow. Here's an example of how selection looks like in `SelectableText`:
![ezgif com-video-to-gif-9](https://user-images.githubusercontent.com/31278849/149620849-9c5798ec-bc5b-49e6-8395-5c860f8eb94f.gif)

**Comment by matthew-carroll** [comment]
@miguelcmedeiros does you still get an error when placing the caret next to an emoji? I'm not getting any errors on either side of emojis on desktop.

One problem that I do see is that the caret movement behavior doesn't understand the full length of the emoji unicode value, so I need to solve that, but I'm not seeing any errors.

**Comment by miguelcmedeiros** [comment]
> @miguelcmedeiros does you still get an error when placing the caret next to an emoji?

I don't get it as well anymore.

**Comment by venkatd** [comment]
Hi @miguelcmedeiros @matthew-carroll  which version of Flutter did you test this on? 

I'm on the following commit:

```
commit 29fd0469ed38e7f81a3e73bbdf06b89907bdba95 (HEAD)
Author: godofredoc <godofredoc@google.com>
Date:   Mon Jan 31 18:06:27 2022 -0800

    Pin dependencies in docker file. (#97466)
```

With the following test:
```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {
  final controller = AttributedTextEditingController(
    text: AttributedText(text: '🐢'),
  );
  runApp(
    MaterialApp(
      home: Center(
        child: SuperDesktopTextField(textController: controller),
      ),
    ),
  );
}
```

And I get a similar error when I run it

<details>
<summary>exception</summary>

```
Restarted application in 264ms.
Reloaded 1 of 942 libraries in 101ms.
Reloaded 1 of 942 libraries in 89ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building BlinkingTextCaret(dirty, state: _BlinkingTextCaretState#5e4c3):
Bad state: No element

The relevant error-causing widget was
SuperDesktopTextField
When the exception was thrown, this was the stack
#0      List.first (dart:core-patch/growable_array.dart:360:5)
#1      SuperSelectableTextState.getCharacterBox
#2      SuperSelectableTextState.getLineHeightAtPosition
#3      _BlinkingTextCaretState.build
#4      StatefulElement.build
#5      ComponentElement.performRebuild
#6      StatefulElement.performRebuild
#7      Element.rebuild
#8      StatefulElement.update
#9      Element.updateChild
#10     SingleChildRenderObjectElement.update
#11     Element.updateChild
#12     RenderObjectElement.updateChildren
#13     MultiChildRenderObjectElement.update
#14     Element.updateChild
#15     SingleChildRenderObjectElement.update
#16     Element.updateChild
#17     SingleChildRenderObjectElement.update
#18     Element.updateChild
#19     ComponentElement.performRebuild
#20     StatefulElement.performRebuild
#21     Element.rebuild
#22     StatefulElement.update
#23     Element.updateChild
#24     RenderObjectElement.updateChildren
#25     MultiChildRenderObjectElement.update
#26     Element.updateChild
#27     SingleChildRenderObjectElement.update
#28     Element.updateChild
#29     SingleChildRenderObjectElement.update
#30     Element.updateChild
#31     SingleChildRenderObjectElement.update
#32     Element.updateChild
#33     SingleChildRenderObjectElement.update
#34     Element.updateChild
#35     SingleChildRenderObjectElement.update
#36     Element.updateChild
#37     SingleChildRenderObjectElement.update
#38     Element.updateChild
#39     ComponentElement.performRebuild
#40     StatefulElement.performRebuild
#41     Element.rebuild
#42     StatefulElement.update
#43     Element.updateChild
#44     SingleChildRenderObjectElement.update
#45     Element.updateChild
#46     ComponentElement.performRebuild
#47     Element.rebuild
#48     ProxyElement.update
#49     Element.updateChild
#50     SingleChildRenderObjectElement.update
#51     Element.updateChild
#52     ComponentElement.performRebuild
#53     Element.rebuild
#54     StatelessElement.update
#55     Element.updateChild
#56     SingleChildRenderObjectElement.update
#57     Element.updateChild
#58     SingleChildRenderObjectElement.update
#59     Element.updateChild
#60     SingleChildRenderObjectElement.update
#61     Element.updateChild
#62     SingleChildRenderObjectElement.update
#63     Element.updateChild
#64     SingleChildRenderObjectElement.update
#65     Element.updateChild
#66     ComponentElement.performRebuild
#67     StatefulElement.performRebuild
#68     Element.rebuild
#69     StatefulElement.update
#70     Element.updateChild
#71     SingleChildRenderObjectElement.update
#72     Element.updateChild
#73     ComponentElement.performRebuild
#74     Element.rebuild
#75     StatelessElement.update
#76     Element.updateChild
#77     ComponentElement.performRebuild
#78     Element.rebuild
#79     StatelessElement.update
#80     Element.updateChild
#81     ComponentElement.performRebuild
#82     StatefulElement.performRebuild
#83     Element.rebuild
#84     StatefulElement.update
#85     Element.updateChild
#86     ComponentElement.performRebuild
#87     Element.rebuild
#88     StatelessElement.update
#89     Element.updateChild
#90     ComponentElement.performRebuild
#91     StatefulElement.performRebuild
#92     Element.rebuild
#93     StatefulElement.update
#94     Element.updateChild
#95     ComponentElement.performRebuild
#96     Element.rebuild
#97     StatelessElement.update
#98     Element.updateChild
#99     SingleChildRenderObjectElement.update
#100    Element.updateChild
#101    ComponentElement.performRebuild
#102    StatefulElement.performRebuild
#103    Element.rebuild
#104    StatefulElement.update
#105    Element.updateChild
#106    ComponentElement.performRebuild
#107    StatefulElement.performRebuild
#108    Element.rebuild
#109    BuildOwner.buildScope
#110    WidgetsBinding.drawFrame
#111    RendererBinding._handlePersistentFrameCallback
#112    SchedulerBinding._invokeFrameCallback
#113    SchedulerBinding.handleDrawFrame
#114    SchedulerBinding._handleDrawFrame
#118    _invoke (dart:ui/hooks.dart:151:10)
#119    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#120    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

```
</details>

I'll try out a newer version of Flutter to see if the error goes away

**Comment by matthew-carroll** [comment]
@venkatd I'm on the latest stable.

Is there more to this test? It doesn't look like any document selection is specified...

**Comment by venkatd** [comment]
@matthew-carroll

I just swapped us to the latest stable and looks like things work on there :)

Not sure why it stopped working on a later commit the master channel.

The exception is the same as in this thread, but it requires no interaction. It happens right when the app loads when trying to render BlinkingTextCaret.

Calculating the lineHeight for the caret uses `getBoxesForSelection`. And it's only triggered if the text is purely emojis because `getBoxesForSelection` doesn't return proper boxes. So assuming it's the same Flutter bug.

Not a priority for us since our whole app can run on the latest stable with no issues. Probably can wait and see if any future stable releases result in a regression.

**Comment by matthew-carroll** [comment]
Can you file a new ticket that includes the repro steps and the specific version of Flutter where you're seeing this?
