### ISSUE TITLE
Deleting multiple nodes throws exception

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#429]
Steps to reproduce:
* Run SuperEditor demo app on macOS
* Introduce a few new nodes to the document
* Select the new nodes
* Press delete or backspace

The following exception is thrown:
```stacktrace
======== Exception caught by widgets library =======================================================
The following _Exception was thrown building DefaultDocumentLayout-[GlobalKey#55777](dirty, state: _DefaultDocumentLayoutState#aa31a):
Exception: No such position in document: [DocumentPosition] - node: "f6de07b8-3889-4b52-9ace-4a75a887e322", position: (TextPosition(offset: 0, affinity: TextAffinity.downstream))

When the exception was thrown, this was the stack: 
#0      MutableDocument.getNodesInside (package:super_editor/src/core/document_editor.dart:203:7)
#1      _DefaultDocumentLayoutState._buildDocComponents (package:super_editor/src/default_editor/layout.dart:480:27)
#2      _DefaultDocumentLayoutState.build (package:super_editor/src/default_editor/layout.dart:455:27)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#21     _invoke (dart:ui/hooks.dart:151:10)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

I the same is done on existing nodes of the demo document, then the exception is not thrown 🤷‍♂️

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll
