### ISSUE TITLE
Problem using the SuperEditor with a TabBar

### ISSUE THREAD

**Issue by hillelcoren** [superlistapp/super_editor#501]
When adding the editor to a TabBarView once the screen is filled with text the TabBarView automatically changes to the next tab rather than scroll down in the editor. 

A related problem is when the editor is used on mobile in a TabBarView if the keyboard is shown it causes the tab bar to change to the previous tab.

Here's a simple example:

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          controller: _controller,
          tabs: [
            Tab(
              text: 'Tab 1',
            ),
            Tab(
              text: 'Tab 2',
            ),
          ],
        ),
      ),
      body: TabBarView(
        controller: _controller,
        children: [
          ExampleEditor(),
          ExampleEditor(),
        ],
      ),
    );
```

**Comment by matthew-carroll** [comment]
@hillelcoren can you provide a video of these two bugs in action? I'm not entirely sure what you're describing.

**Comment by hillelcoren** [comment]
I've retested using the editor in tabs, I'm no longer able to reproduce the issue above but I'm seeing this error in the console.

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'


When the exception was thrown, this was the stack
#2      ScrollController.position
#3      _AndroidDocumentTouchInteractorState.scrollPosition
#4      _AndroidDocumentTouchInteractorState._updateScrollPositionListener
#5      _AndroidDocumentTouchInteractorState.initState.<anonymous closure>
#6      SchedulerBinding._invokeFrameCallback
#7      SchedulerBinding.handleDrawFrame
#8      SchedulerBinding._handleDrawFrame
#12     _invoke (dart:ui/hooks.dart:151:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#14     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 18 pixels on the bottom.
The relevant error-causing widget was
SuperEditor
════════════════════════════════════════════════════════════════════════════════
```

**Comment by matthew-carroll** [comment]
@hillelcoren is that problem caused by the widget tree you originally posted? Does it happen immediately upon loading the UI?

**Comment by hillelcoren** [comment]
Yes, this is trigged by the widget tree above.

The error occurs when I type into the super editor enough lines of text to get to the bottom of the screen.
