### ISSUE TITLE
ENTER key on web no longer works in documents

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#587]
On web, pressing `enter` doesn't trigger `performAction()`. This same problem exists for Android. On Android, we look for a `\n` character and then insert a new paragraph. We need to do the same thing for web.

UPDATE - the following errors are being moved to a different ticket:

Also, various interactions with Super Editor on web with IME results in errors like the following.

```
(55.711) editor.keys > INFO: Handling key press: RawKeyDownEvent#6504f(logicalKey: LogicalKeyboardKey#b2c0d(keyId: "0x10000000d", keyLabel: "Enter", debugName: "Enter"), physicalKey: PhysicalKeyboardKey#70028(usbHidUsage: "0x00070028", debugName: "Enter"), repeat: false)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:51130/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:51130/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:51130/dart_sdk.js:192844:105)
    at Function.inferDeltaState (http://localhost:51130/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange (http://localhost:51130/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:51130/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:51130/dart_sdk.js:5284:17)
    at HTMLTextAreaElement.<anonymous> (http://localhost:51130/dart_sdk.js:109003:100)
```

**Comment by matthew-carroll** [comment]
I filed https://github.com/flutter/flutter/issues/104944 with Flutter because this stack trace doesn't make it clear where things went wrong. I don't know if this is a Super Editor bug or a Flutter web bug.

**Comment by matthew-carroll** [comment]
@angelosilvestre - I'm going to assign this to you so that you have more tickets to work through on your schedule.

**Comment by angelosilvestre** [comment]
UPDATE:

The fix for the ENTER key behavior was straightforward.

> Also, various interactions with Super Editor on web with IME results in errors like the following.

This is a bit more tricky. I was able to reproduce this issue with this example:

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Issue587(),
      ),
    );
  }
}

class Issue587 extends StatefulWidget {
  const Issue587({Key? key}) : super(key: key);

  @override
  State<Issue587> createState() => _Issue587State();
}

class _Issue587State extends State<Issue587> {  
  late DocumentEditor _editor;  

  @override
  void initState() {
    super.initState();
    _editor = DocumentEditor(
      document: MutableDocument(
        nodes: [
          ParagraphNode(
            id: '1',
            text: AttributedText(text:"A"),
          ),      
          ParagraphNode(
            id: '2',
            text: AttributedText(text: "B"),
          ),
          ParagraphNode(
            id: '3',
            text: AttributedText(text: "C"),
          ),    
        ],
      )
    );
  }

  @override
  Widget build(BuildContext context) {
    return  SuperEditor(
      editor: _editor,                  
      gestureMode: DocumentGestureMode.mouse,
      inputSource: DocumentInputSource.ime,
      keyboardActions: defaultImeKeyboardActions,
    );
  }
}
```

Steps to reproduce:

1. Tap after C
2. Press Shift
3. Press UP Arrow 2 times
4. Type another letter

After this the crash happens.

Here's the method where the error happens in js:

```javascript
static inferDeltaState(newEditingState, lastEditingState, lastTextEditingDeltaState) {
      let t263, t263$;
      let newTextEditingDeltaState = lastTextEditingDeltaState.copyWith();	  
      let previousSelectionWasCollapsed = (t263 = lastEditingState, t263 == null ? null : t263.baseOffset) == (t263$ = lastEditingState, t263$ == null ? null : t263$.extentOffset);      
	  let isTextBeingRemoved = newTextEditingDeltaState.deltaText[$isEmpty] && newTextEditingDeltaState.deltaEnd !== -1;      
	  let isTextBeingChangedAtActiveSelection = newTextEditingDeltaState.deltaText[$isNotEmpty] && !previousSelectionWasCollapsed;	  
      if (isTextBeingRemoved) {
        let deletedLength = newTextEditingDeltaState.oldText.length - dart.nullCheck(newEditingState.text).length;		
        newTextEditingDeltaState.deltaStart = newTextEditingDeltaState.deltaEnd - deletedLength;		
      } else if (isTextBeingChangedAtActiveSelection) {
        newTextEditingDeltaState.deltaStart = dart.nullCheck(dart.nullCheck(lastEditingState).baseOffset);		
      }
      let isCurrentlyComposing = newTextEditingDeltaState.composingOffset != null && newTextEditingDeltaState.composingOffset != newTextEditingDeltaState.composingExtent;	  
      if (newTextEditingDeltaState.deltaText[$isNotEmpty] && previousSelectionWasCollapsed && isCurrentlyComposing) {
        newTextEditingDeltaState.deltaStart = dart.nullCheck(newTextEditingDeltaState.composingOffset);
        newTextEditingDeltaState.deltaEnd = dart.nullCheck(newTextEditingDeltaState.composingExtent);
      }	  
      let isDeltaRangeEmpty = newTextEditingDeltaState.deltaStart === -1 && newTextEditingDeltaState.deltaStart === newTextEditingDeltaState.deltaEnd;	  
      if (!isDeltaRangeEmpty) {
        let replacementRange = new ui.TextRange.new({start: newTextEditingDeltaState.deltaStart, end: newTextEditingDeltaState.deltaEnd});
		console.log("replacementRange: " + replacementRange);
		console.log("newTextEditingDeltaState.oldText: " + newTextEditingDeltaState.oldText);
		console.log("newTextEditingDeltaState.deltaText: " + newTextEditingDeltaState.deltaText);		
        // the exception happens here
        let textAfterDelta = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, replacementRange);
        let isDeltaVerified = textAfterDelta === dart.nullCheck(newEditingState.text);
        if (!isDeltaVerified) {
          let isPeriodInsertion = newTextEditingDeltaState.deltaText[$contains](".");
          let deltaTextPattern = core.RegExp.new(core.RegExp.escape(newTextEditingDeltaState.deltaText));
          for (let match of deltaTextPattern.allMatches(dart.nullCheck(newEditingState.text))) {
            let textAfterMatch = null;
            let actualEnd = null;
            let isMatchWithinOldTextBounds = match.start >= 0 && match.end <= newTextEditingDeltaState.oldText.length;
            if (!isMatchWithinOldTextBounds) {
              actualEnd = match.start + newTextEditingDeltaState.deltaText.length - 1;
              textAfterMatch = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, new ui.TextRange.new({start: match.start, end: actualEnd}));
            } else {
              actualEnd = actualEnd = isPeriodInsertion ? match.end - 1 : match.end;
              textAfterMatch = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, new ui.TextRange.new({start: match.start, end: actualEnd}));
            }
            if (textAfterMatch === dart.nullCheck(newEditingState.text)) {
              newTextEditingDeltaState.deltaStart = match.start;
              newTextEditingDeltaState.deltaEnd = actualEnd;
              break;
            }
          }
        }
      }
      newTextEditingDeltaState.baseOffset = dart.nullCheck(newEditingState.baseOffset);
      newTextEditingDeltaState.extentOffset = dart.nullCheck(newEditingState.extentOffset);
      return newTextEditingDeltaState;
    } 
```

I added some logs to get some information, this is what was logged:

```
replacementRange: TextRange(start: 1, end: 5)
newTextEditingDeltaState.oldText: C
newTextEditingDeltaState.deltaText: e
```
This method is called here:

```javascript
handleChange(event) {
      if (!this.isEnabled) dart.assertFailed(null, I[144], 1231, 12, "isEnabled");
      let newEditingState = _engine.EditingState.fromDomElement(this.activeDomElement);
      let newTextEditingDeltaState = null;
      if (this.inputConfiguration.enableDeltaModel) {
        newTextEditingDeltaState = _engine.TextEditingDeltaState.inferDeltaState(newEditingState, this.lastEditingState, this.editingDeltaState);
      }
      if (!newEditingState._equals(this.lastEditingState)) {
        this.lastEditingState = newEditingState;
        this[_editingDeltaState] = newTextEditingDeltaState;
        dart.nullCheck(this.onChange)(this.lastEditingState, this[_editingDeltaState]);
        this[_editingDeltaState] = null;
      }
    }
```

Just for testing I commented line 145 in `document_input_ime.dart` and the exception stopped, but, of course, the application doesn't work as expected without calling `_syncImeWithDocumentAndComposer`:

https://github.com/superlistapp/super_editor/blob/a67b332367d33e1cb4fc295f540635a897853dab/super_editor/lib/src/default_editor/document_input_ime.dart#L131-L150

**Comment by matthew-carroll** [comment]
@angelosilvestre let's ensure that any update includes some kind of conclusion and next steps. Is this a Flutter bug or a super_editor bug? Where do you think we should go from here?

**Comment by angelosilvestre** [comment]
@matthew-carroll  It's still unclear to me if this is a Flutter web bug or a super_editor bug. I think we could merge the fix for the ENTER key and then I could try to investigate deeper to see if I could determine if this is a super_editor bug.

**Comment by matthew-carroll** [comment]
Ok. Can you file a new issue that describes the non-enter error? I'll update the original ticket to only refer to pressing enter.
