### ISSUE TITLE
Exception after replacing paragraph on web

### ISSUE THREAD

**Issue by angelosilvestre** [superlistapp/super_editor#650]
On web, replacing the content of two paragraphs causes this exception:

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:431:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
    at Object.throw_ [as throw] (http://localhost:64936/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:64936/dart_sdk.js:5005:15)
    at Object._replace (http://localhost:64936/dart_sdk.js:192844:105)
    at TextEditingDeltaState.inferDeltaState (http://localhost:64936/dart_sdk.js:185414:38)
    at _engine.GloballyPositionedTextEditingStrategy.new.handleChange (http://localhost:64936/dart_sdk.js:178091:66)
    at Object._checkAndCall (http://localhost:64936/dart_sdk.js:5279:16)
    at Object.dcall (http://localhost:64936/dart_sdk.js:5284:17)
    at HTMLTextAreaElement.<anonymous> (http://localhost:64936/dart_sdk.js:109003:100)
```
Reproducible example: 

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

void main() {  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Issue(),
      ),
    );
  }
}

class Issue extends StatefulWidget {
  const Issue({Key? key}) : super(key: key);

  @override
  State<Issue> createState() => _IssueState();
}

class _IssueState extends State<Issue> {  
  late DocumentEditor _editor;  

  @override
  void initState() {
    super.initState();
    _editor = DocumentEditor(
      document: MutableDocument(
        nodes: [
          ParagraphNode(
            id: '1',
            text: AttributedText(text:"A"),
          ),      
          ParagraphNode(
            id: '2',
            text: AttributedText(text: "B"),
          ),
          ParagraphNode(
            id: '3',
            text: AttributedText(text: "C"),
          ),    
        ],
      )
    );
  }

  @override
  Widget build(BuildContext context) {
    return  SuperEditor(
      editor: _editor,                  
      gestureMode: DocumentGestureMode.mouse,
      inputSource: DocumentInputSource.ime,
      keyboardActions: defaultImeKeyboardActions,
    );
  }
}
```

Steps to reproduce:

1. Tap after C
2. Press Shift
3. Press UP Arrow 2 times
4. Type another letter

After this the crash happens.

Here's the method where the error happens in js:

```javascript
static inferDeltaState(newEditingState, lastEditingState, lastTextEditingDeltaState) {
      let t263, t263$;
      let newTextEditingDeltaState = lastTextEditingDeltaState.copyWith();	  
      let previousSelectionWasCollapsed = (t263 = lastEditingState, t263 == null ? null : t263.baseOffset) == (t263$ = lastEditingState, t263$ == null ? null : t263$.extentOffset);      
	  let isTextBeingRemoved = newTextEditingDeltaState.deltaText[$isEmpty] && newTextEditingDeltaState.deltaEnd !== -1;      
	  let isTextBeingChangedAtActiveSelection = newTextEditingDeltaState.deltaText[$isNotEmpty] && !previousSelectionWasCollapsed;	  
      if (isTextBeingRemoved) {
        let deletedLength = newTextEditingDeltaState.oldText.length - dart.nullCheck(newEditingState.text).length;		
        newTextEditingDeltaState.deltaStart = newTextEditingDeltaState.deltaEnd - deletedLength;		
      } else if (isTextBeingChangedAtActiveSelection) {
        newTextEditingDeltaState.deltaStart = dart.nullCheck(dart.nullCheck(lastEditingState).baseOffset);		
      }
      let isCurrentlyComposing = newTextEditingDeltaState.composingOffset != null && newTextEditingDeltaState.composingOffset != newTextEditingDeltaState.composingExtent;	  
      if (newTextEditingDeltaState.deltaText[$isNotEmpty] && previousSelectionWasCollapsed && isCurrentlyComposing) {
        newTextEditingDeltaState.deltaStart = dart.nullCheck(newTextEditingDeltaState.composingOffset);
        newTextEditingDeltaState.deltaEnd = dart.nullCheck(newTextEditingDeltaState.composingExtent);
      }	  
      let isDeltaRangeEmpty = newTextEditingDeltaState.deltaStart === -1 && newTextEditingDeltaState.deltaStart === newTextEditingDeltaState.deltaEnd;	  
      if (!isDeltaRangeEmpty) {
        let replacementRange = new ui.TextRange.new({start: newTextEditingDeltaState.deltaStart, end: newTextEditingDeltaState.deltaEnd});
		console.log("replacementRange: " + replacementRange);
		console.log("newTextEditingDeltaState.oldText: " + newTextEditingDeltaState.oldText);
		console.log("newTextEditingDeltaState.deltaText: " + newTextEditingDeltaState.deltaText);		
        // the exception happens here
        let textAfterDelta = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, replacementRange);
        let isDeltaVerified = textAfterDelta === dart.nullCheck(newEditingState.text);
        if (!isDeltaVerified) {
          let isPeriodInsertion = newTextEditingDeltaState.deltaText[$contains](".");
          let deltaTextPattern = core.RegExp.new(core.RegExp.escape(newTextEditingDeltaState.deltaText));
          for (let match of deltaTextPattern.allMatches(dart.nullCheck(newEditingState.text))) {
            let textAfterMatch = null;
            let actualEnd = null;
            let isMatchWithinOldTextBounds = match.start >= 0 && match.end <= newTextEditingDeltaState.oldText.length;
            if (!isMatchWithinOldTextBounds) {
              actualEnd = match.start + newTextEditingDeltaState.deltaText.length - 1;
              textAfterMatch = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, new ui.TextRange.new({start: match.start, end: actualEnd}));
            } else {
              actualEnd = actualEnd = isPeriodInsertion ? match.end - 1 : match.end;
              textAfterMatch = _engine._replace(newTextEditingDeltaState.oldText, newTextEditingDeltaState.deltaText, new ui.TextRange.new({start: match.start, end: actualEnd}));
            }
            if (textAfterMatch === dart.nullCheck(newEditingState.text)) {
              newTextEditingDeltaState.deltaStart = match.start;
              newTextEditingDeltaState.deltaEnd = actualEnd;
              break;
            }
          }
        }
      }
      newTextEditingDeltaState.baseOffset = dart.nullCheck(newEditingState.baseOffset);
      newTextEditingDeltaState.extentOffset = dart.nullCheck(newEditingState.extentOffset);
      return newTextEditingDeltaState;
    } 
```

I added some logs to get some information, this is what was logged:

```
replacementRange: TextRange(start: 1, end: 5)
newTextEditingDeltaState.oldText: C
newTextEditingDeltaState.deltaText: e
```
This method is called here:

```javascript
handleChange(event) {
      if (!this.isEnabled) dart.assertFailed(null, I[144], 1231, 12, "isEnabled");
      let newEditingState = _engine.EditingState.fromDomElement(this.activeDomElement);
      let newTextEditingDeltaState = null;
      if (this.inputConfiguration.enableDeltaModel) {
        newTextEditingDeltaState = _engine.TextEditingDeltaState.inferDeltaState(newEditingState, this.lastEditingState, this.editingDeltaState);
      }
      if (!newEditingState._equals(this.lastEditingState)) {
        this.lastEditingState = newEditingState;
        this[_editingDeltaState] = newTextEditingDeltaState;
        dart.nullCheck(this.onChange)(this.lastEditingState, this[_editingDeltaState]);
        this[_editingDeltaState] = null;
      }
    }
```

Just for testing I commented line 145 in `document_input_ime.dart` and the exception stopped, but, of course, the application doesn't work as expected without calling `_syncImeWithDocumentAndComposer`:

https://github.com/superlistapp/super_editor/blob/a67b332367d33e1cb4fc295f540635a897853dab/super_editor/lib/src/default_editor/document_input_ime.dart#L131-L150

It's unclear if this is a Flutter Web bug or a SuperEditor bug.

**Comment by matthew-carroll** [comment]
@angelosilvestre do you want to look at this again to see if you're able to tell whether this is Flutter or us?

**Comment by angelosilvestre** [comment]
@matthew-carroll After https://github.com/flutter/engine/pull/44806 this issue doesn't happen anymore.

**Comment by matthew-carroll** [comment]
Closing due to Flutter engine fix
