### ISSUE TITLE
Platform Exception on Android

### ISSUE THREAD

**Issue by MenuItem207** [superlistapp/super_editor#791]
Steps to replicate:
1. Create a Super Editor:
```
SuperEditor(
  inputSource:
      DocumentInputSource.ime,
  editor: DocumentEditor(
    document: MutableDocument(
      nodes: [
        ParagraphNode(
          id: DocumentEditor
              .createNodeId(),
          text: AttributedText(
            text: '',
          ),
        ),
      ],
    ),
  ),
)
```

2. Type in 'Abc' 
3. Hit Enter
4. Type in 'a'
5. Backspace all the way until A
6. Repeat steps 2 - 5 once
7. Exception:

```
Exception has occurred.
PlatformException (PlatformException(error, invalid composing start: 0, null, java.lang.IndexOutOfBoundsException: invalid composing start: 0
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:777)
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:738)
	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:101)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
))
```

**Comment by angelosilvestre** [comment]
This seems to be a Flutter bug.
I filed https://github.com/flutter/flutter/issues/113253

**Comment by matthew-carroll** [comment]
Despite the related Flutter bug, we believe we've solved this issue on our end, so I'm going to close this ticket.
