### ISSUE TITLE
Exception thrown when editing back and forth into a document

### ISSUE THREAD

**Issue by ramsestom** [superlistapp/super_editor#809]
Tested it on android

How to reproduce the issue:
1. Create a SuperEditor with a MutableDocument with some text
```
SuperEditor(
  inputSource: DocumentInputSource.ime,
  editor: DocumentEditor(
    document: MutableDocument(
      nodes: [
        ParagraphNode(
          id: DocumentEditor .createNodeId(),
          text: AttributedText(
            text: 'This is a test',
          ),
        ),
      ],
    ),
  ),
) 
```
2. click (tap) to put the caret at the end of the document (after the 't' of 'test' in this example)
3. click to put the caret somewhere in the middle of the document (after the 's' of the first word 'This' for example)

alternatively you can

3. put a line break by pressing enter
4. on the new line, enter some random text
5. click to put the caret at the end of the first line of the document (after the 't' of word 'test' in this example)
6. click to put back the caret at the end of the document (the end of line 2 you typed at step 4)

In both cases, you would receive an exception:

```
════════ Exception caught by services library ══════════════════════════════════
The following StateError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Bad state: No element

When the exception was thrown, this was the stack
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      _DocumentImeInteractorState.updateEditingValueWithDeltas
package:super_editor/…/default_editor/document_input_ime.dart:291
#2      TextInput._handleTextInputInvocation
package:flutter/…/services/text_input.dart:1814
#3      TextInput._loudlyHandleTextInputInvocation
package:flutter/…/services/text_input.dart:1701
#4      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:536
#5      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:529
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:387
#7      _invoke2 (dart:ui/hooks.dart:186:13)
#8      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#9      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#10     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: []}])
═══════════════════════════════════════════════════════════════════════════════
```

This is due to the line `_syncImeWithDocumentAndComposer(textEditingDeltas.last.composing);` in the `updateEditingValueWithDeltas` function from the `document_input_ime.dart` file where `.last` is called on an empty `textEditingDeltas` list.

I tried to add the line `if (textEditingDeltas.isEmpty){return;}` at the start of the `updateEditingValueWithDeltas` function to prevent this bug but I still get an exception with the alternative test (two lines of text in the document) after doing this:

```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<DocumentSelection?>:
Range start 10 is out of text of length 4
'package:flutter/src/services/text_input.dart':
package:flutter/…/services/text_input.dart:1
Failed assertion: line 968 pos 12: 'range.start >= 0 && range.start <= text.length'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      TextEditingValue._textRangeIsValid
package:flutter/…/services/text_input.dart:968
#3      TextEditingValue.toJSON
package:flutter/…/services/text_input.dart:924
#4      TextInput._setEditingState
package:flutter/…/services/text_input.dart:1889
#5      TextInputConnection.setEditingState
package:flutter/…/services/text_input.dart:1336
#6      _DocumentImeInteractorState.currentTextEditingValue=
package:super_editor/…/default_editor/document_input_ime.dart:225
#7      _DocumentImeInteractorState._syncImeWithDocumentAndComposer
package:super_editor/…/default_editor/document_input_ime.dart:264
#8      _DocumentImeInteractorState._onComposerChange
package:super_editor/…/default_editor/document_input_ime.dart:145
#9      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:351
#10     ValueNotifier.value=
package:flutter/…/foundation/change_notifier.dart:456
#11     DocumentComposer.selection=
package:super_editor/…/core/document_composer.dart:43
#12     _AndroidDocumentTouchInteractorState._selectPosition
package:super_editor/…/default_editor/document_gestures_touch_android.dart:833
#13     _AndroidDocumentTouchInteractorState._onTapUp
package:super_editor/…/default_editor/document_gestures_touch_android.dart:420
#14     TapSequenceGestureRecognizer._checkUp.<anonymous closure>
package:super_editor/…/infrastructure/multi_tap_gesture.dart:337
#15     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#16     TapSequenceGestureRecognizer._checkUp
package:super_editor/…/infrastructure/multi_tap_gesture.dart:337
#17     TapSequenceGestureRecognizer._registerFirstTap
package:super_editor/…/infrastructure/multi_tap_gesture.dart:277
#18     TapSequenceGestureRecognizer._handleEvent
package:super_editor/…/infrastructure/multi_tap_gesture.dart:157
#19     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
#20     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#22     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:141
#23     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:127
#24     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:460
#25     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
#26     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
#27     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
#28     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
#29     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
#30     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
#31     _invoke1 (dart:ui/hooks.dart:167:13)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 2 frames from class _AssertionError)
The ValueNotifier<DocumentSelection?> sending notification was: ValueNotifier<DocumentSelection?>#8d068([DocumentSelection] - 
  base: ([DocumentPosition] - node: "9363bb11-9367-4952-adc5-060e3989ff0f", position: (TextPosition(offset: 4, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "9363bb11-9367-4952-adc5-060e3989ff0f", position: (TextPosition(offset: 4, affinity: TextAffinity.downstream))))
═══════════════════════════════════════════════════════════════════════════════
```
So it looks like this bug would be a bit more complex to fix than just testing if the platform is sending us an empty `textEditingDeltas` list and ignore it in that case...

**Comment by matthew-carroll** [comment]
Are you using the latest version of `super_editor` from GitHub, or from pub.dev?

**Comment by matthew-carroll** [comment]
@ramsestom - can you please answer my question above?

**Comment by ramsestom** [comment]
> @ramsestom - can you please answer my question above?

I am using the latest version from pub.dev (super_editor 0.2.2)

**Comment by matthew-carroll** [comment]
@ramsestom can you try again on `main`, please? The pub version is far behind our `main` branch.

**Comment by ramsestom** [comment]
@matthew-carroll I tested with the main branch from github, as requested, and the problem is exactly the same.

**Comment by matthew-carroll** [comment]
@angelosilvestre can you take a look at this?

**Comment by angelosilvestre** [comment]
@matthew-carroll Analyzing the logs, this seems to be the same issue of https://github.com/superlistapp/super_editor/issues/791

**Comment by matthew-carroll** [comment]
Ok. I'm going to close this in favor of #791. @ramsestom if this issue continues after the resolution of #791, please open a new ticket.
