### ISSUE TITLE
[SuperEditor] - Creating new tasks eventually blows up

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#949]
Repro: Run the example app. Place the caret at the end of a task. Press `enter` to create a new task. Type something. Repeat many times.

Expected: New tasks are created forever, and characters are entered.

Actual: Eventually, an error occurs and we lose IME input.

```
======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:252:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:13)
#2      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:102:46)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:40:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:336:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1875:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1761:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#11     _invoke2 (dart:ui/hooks.dart:183:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 4, oldText: . sf, selectionAffinity: TextAffinity.downstream, deltaEnd: 3, deltaText: a, deltaStart: 3, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 4, composingBase: -1}]}])
====================================================================================================
```

**Comment by matthew-carroll** [comment]
Update: this problem isn't specific to task items, it happens with regular paragraphs, too.

The problem may or may not be related to speed of text entry. If it's speed related, then this issue might be a duplicate of https://github.com/superlistapp/super_editor/issues/914

**Comment by matthew-carroll** [comment]
After investigation, I believe that this issue is a duplicate of #914 - closing this one in favor of that one.
