### ISSUE TITLE
[SuperEditor] - IME error when entering text at beginning of block

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#954]
Repro: Run the example app. Place the caret at the beginning of a paragraph. Type a character key to insert the character. If the first character is inserted, press a second character key.

Expected: Character is inserted.

Actual: Exception

```
======== Exception caught by services library ======================================================
The following _TypeError was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:109:6)
#1      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:41:9)
#2      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:186:30)
#3      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1875:63)
#5      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1761:20)
#6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#9      _invoke2 (dart:ui/hooks.dart:183:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 1, oldText: , selectionAffinity: TextAffinity.upstream, deltaEnd: 0, deltaText: j, deltaStart: 0, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 1, composingBase: -1}]}])
====================================================================================================
```

**Comment by matthew-carroll** [comment]
Also, placing the caret at the end of a paragraph and typing causes the new text to appear at the beginning of the paragraph.
