### ISSUE TITLE
[SuperEditor][iOS] Selection is broken after `doc.replaceNode` on the selected node

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#968]
# Environment

```
SuperEditor: stable branch
Flutter: 3.3.10
iOS Device
```

# Steps

**Note**: I think it's required to have different font sizes between the nodes

1. Place cursor on a specific node (i.e. ParagraphNode)
2. Call `doc.replaceNode` and update it to ListItemNode for example

This exception will be thrown:

```bash
[log] Null check operator used on a null value
[log] #0      _IOSDocumentTouchInteractorState._positionExpandedSelectionHandles
package:super_editor/…/default_editor/document_gestures_touch_ios.dart:917
#1      _IOSDocumentTouchInteractorState._updateHandlesAfterSelectionOrLayoutChange
package:super_editor/…/default_editor/document_gestures_touch_ios.dart:377
#2      _IOSDocumentTouchInteractorState._onDocumentChange.<anonymous closure>
package:super_editor/…/default_editor/document_gestures_touch_ios.dart:343
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1113
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#6      _rootRun (dart:async/zone.dart:1391:13)
#7      _CustomZone.run (dart:async/zone.dart:1293:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#9      _invoke (dart:ui/hooks.dart:150:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#11     _drawFrame (dart:ui/hooks.dart:115:31)
```

Then, I tried tapping on another node and (not always) this exception was thrown:

```bash
[log] Null check operator used on a null value
[log] #0      _IOSDocumentTouchInteractorState._isOverBaseHandle
package:super_editor/…/default_editor/document_gestures_touch_ios.dart:693
#1      _IOSDocumentTouchInteractorState._onTapUp
package:super_editor/…/default_editor/document_gestures_touch_ios.dart:446
#2      TapSequenceGestureRecognizer._checkUp.<anonymous closure>
package:super_editor/…/infrastructure/multi_tap_gesture.dart:337
#3      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#4      TapSequenceGestureRecognizer._checkUp
package:super_editor/…/infrastructure/multi_tap_gesture.dart:337
#5      TapSequenceGestureRecognizer._registerFirstTap
package:super_editor/…/infrastructure/multi_tap_gesture.dart:277
#6      TapSequenceGestureRecognizer._handleEvent
package:super_editor/…/infrastructure/multi_tap_gesture.dart:157
#7      PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#10     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:141
#11     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:127
#12     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:460
#13     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
#14     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
#15     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
#16     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
#17     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
#18     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
#19     _invoke1 (dart:ui/hooks.dart:167:13)
```

**Comment by raulmabe-labhouse** [comment]
Fixed it by calling `composer.selectionNotifier.value = DocumentSelection.collapsed(position: position.copyWith(nodeId: newNodeId));` with the new node id.

**Comment by angelosilvestre** [comment]
@raulmabe-labhouse Could you please attach a reproducible sample? I wasn't able to reproduce this issue on the latest stable.
