### ISSUE TITLE
[SuperEditor][iOS] Writing at the end of a document after 2 consecutive break lines will throw an exception

### ISSUE THREAD

**Issue by raulmabe-labhouse** [superlistapp/super_editor#970]
# Environment
```
SuperEditor: main
Flutter: master
Reproduced with the /example on iOS
```

This bug is not present on macOS.

# Steps

1. Place the caret at the end the document
2. Insert two consecutive break lines
3. Try to write something and the following exception is thrown and nothing is written

```
[log] Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset: 3, affinity: TextAffinity.downstream)
[log] #0      DocumentImeSerializer._imeToDocumentPosition
package:super_editor/…/document_ime/document_serialization.dart:254
#1      DocumentImeSerializer.imeToDocumentSelection
package:super_editor/…/document_ime/document_serialization.dart:163
#2      TextDeltasDocumentEditor._applyInsertion
package:super_editor/…/document_ime/document_delta_editing.dart:104
#3      TextDeltasDocumentEditor.applyDeltas
package:super_editor/…/document_ime/document_delta_editing.dart:41
#4      DocumentImeInputClient.updateEditingValueWithDeltas
package:super_editor/…/document_ime/document_ime_communication.dart:197
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas
package:super_editor/…/document_ime/ime_decoration.dart:119
#6      TextInput._handleTextInputInvocation
package:flutter/…/services/text_input.dart:1814
#7      TextInput._loudlyHandleTextInputInvocation
package:flutter/…/services/text_input.dart:1701
#8      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:536
#9      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:529
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
package:flutter/…/services/binding.dart:387
#11     _invoke2 (dart:ui/hooks.dart:186:13)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

Similar exception as the one mentioned in #930

**Comment by angelosilvestre** [comment]
@raulmabe-labhouse This seems to be resolved after https://github.com/superlistapp/super_editor/pull/974.

Could you please confirm if it's still an issue?

**Comment by raulmabe-labhouse** [comment]
It's resolved, thank you very much @angelosilvestre
