### ISSUE TITLE
[SuperEditor] 2 carets are painted when long-press the SPACE key on iOS

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#992]
Steps to reproduce:
* Using `stable` branch, open the demo app on an iOS device
* Place the selection in the text
* On the software keyboard, long press the SPACE key

Expected: show only floating cursor (probably that looks the same as the selection caret)
Actual: shows a floating cursor (red) and the selection caret (blue) that follows closely the floating cursor

https://user-images.githubusercontent.com/31278849/214280623-8f5d2455-6508-4a03-aebd-da78ec3d6fc9.MP4

**Comment by miguelcmedeiros** [comment]
For reference I took this recording from the Notes app

https://user-images.githubusercontent.com/31278849/214281398-bd3e0d8b-afa2-4770-8ba9-e8c0f0946c8f.MP4

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by miguelcmedeiros** [comment]
Also, while making the recording I got this exception:
```
======== Exception caught by foundation library ====================================================
The following _CastError was thrown while dispatching notifications for FloatingCursorController:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _IosDocumentTouchEditingControlsState._onFloatingCursorChange (package:super_editor/src/infrastructure/platforms/ios/ios_document_controls.dart:214:42)
#1      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351:24)
#2      FloatingCursorController.offset= (package:super_editor/src/infrastructure/platforms/ios/ios_document_controls.dart:616:5)
#3      DocumentImeInputClient.updateFloatingCursor (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:300:36)
#4      DeltaTextInputClientDecorator.updateFloatingCursor (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:124:14)
#5      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1827:37)
#6      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1701:20)
#7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
#8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#10     _invoke2 (dart:ui/hooks.dart:186:13)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
The FloatingCursorController sending notification was: Instance of 'FloatingCursorController'
====================================================================================================
```

Not sure at what point this happened. Start of long press, during or when releasing the key 🤷‍♂️

**Comment by matthew-carroll** [comment]
@miguelcmedeiros if you look closely at your Notes app example, there are two carets there, too. This is iOS's "floating cursor" feature. We implemented that on purpose.

It looks like the color of the caret in our editor is blue when it should be grey, but other than that, I think this is behaving as intended, right?

**Comment by miguelcmedeiros** [comment]
It seems that the grey caret only shows when the cursor is not on top of the text, so that it gives an indication of where the selection will land once the user releases the key.
